import type { PostBuilderCopy } from './types';

export const DEFAULT_POST_BUILDER_COPY: PostBuilderCopy = {
	pageTitle: 'Create post',
	pageDescription: 'Turn real work into posts tailored to each destination.',
	builderMode: 'Builder',
	manualMode: 'Manual',
	creationModeLabel: 'Post creation mode',
	builderInputModeLabel: 'Builder input mode',
	fromSourceMode: 'From source',
	discoverMode: 'Discover',
	builderInputHeading: 'What happened?',
	builderInputDescription:
		'Share an idea, update, link, or file. OpenPost will find the best way to post it.',
	sourcePlaceholder: 'I just deleted 15,000 lines and somehow the product got better.',
	attach: 'Attach',
	pasteLink: 'Paste link',
	record: 'Record',
	addContext: 'Add context',
	removeSource: 'Remove source',
	sourceMaterialLabel: 'Source material',
	voice: 'Voice',
	destinations: 'Destinations',
	direction: 'Direction',
	buildPost: 'Build post',
	buildOpportunity: 'Build selected opportunity',
	buildingPost: 'Building post',
	privacyNote: '',
	whatHappensHeading: 'OpenPost will',
	whatHappensSteps: [
		'Find the strongest angle',
		'Write for each destination',
		'Plan useful media',
		'Send the draft to the composer'
	],
	inspirationHeading: 'Need a starting point?',
	inspirationDescription: 'Pick an idea, then add what actually happened.',
	loadMoreIdeas: 'Load more ideas',
	discoverHeading: 'Content opportunities',
	discoverDescription: 'Choose a timely subject that fits your work and audience.',
	discoverEmptyTitle: 'No opportunities yet',
	discoverEmptyDescription: 'Refresh the feed or build from your own source.',
	refreshDiscover: 'Refresh',
	loadMoreOpportunities: 'Load more',
	loadingOpportunities: 'Loading content opportunities',
	whyThisFits: 'Why this fits',
	possibleAngles: 'Possible angles',
	chooseAngle: 'Choose angle',
	selectedAngle: 'Selected angle',
	recommendedTreatment: 'Recommended treatment',
	selectOpportunity: 'Use this opportunity',
	selectedOpportunity: 'Selected',
	buildProgressHeading: 'Building your post',
	reviewingDraft: 'Checking claims, voice, and platform fit',
	buildCancelled: 'Build cancelled. Your source is still here.',
	cancelBuild: 'Cancel',
	retryBuild: 'Try again',
	resultHeading: 'Your draft package is ready',
	resultDescription: 'Review the route, claims, and media plan before opening the composer.',
	coreThesis: 'Core thesis',
	reviewInComposer: 'Review in composer',
	openingComposer: 'Opening composer',
	buildAnother: 'Build another',
	angle: 'Angle',
	goal: 'Goal',
	audience: 'Audience',
	voiceUsed: 'Voice',
	destinationPlan: 'Destination plan',
	claimReview: 'Claim review',
	mediaPlan: 'Media plan',
	makeMeme: 'Make this meme',
	createVisual: 'Create this visual',
	annotateSource: 'Annotate source',
	createVideo: 'Create video',
	editVideo: 'Edit source video',
	preparingMedia: 'Opening media tool',
	evidenceOnly: 'Evidence only',
	mayPublish: 'Can use in the post',
	included: 'Included',
	skipped: 'Skipped',
	needsReview: 'Needs review',
	supported: 'Supported by source',
	userAsserted: 'You supplied this fact',
	opinion: 'Opinion',
	parody: 'Parody',
	needsVerification: 'Needs verification',
	noClaimsNeedReview: 'No claims need review.',
	workspaceRequired: 'Choose a workspace before building.',
	sourceRequired: 'Add a note, link, or file before building.',
	opportunityRequired: 'Choose an opportunity before building.',
	destinationsRequired: 'Choose at least one destination.',
	requestFailed: 'OpenPost could not finish this build. Try again.',
	dismissError: 'Dismiss error',
	builderHelpLabel: 'Builder help',
	footerNote:
		'The builder makes the first draft. You review and edit every rendition in the composer.'
};

export function postBuilderCopy(overrides: Partial<PostBuilderCopy> = {}): PostBuilderCopy {
	return {
		...DEFAULT_POST_BUILDER_COPY,
		...overrides,
		whatHappensSteps: overrides.whatHappensSteps ?? DEFAULT_POST_BUILDER_COPY.whatHappensSteps
	};
}
