import { m } from '$lib/paraglide/messages';
import type { PostBuilderCopy } from './types';

export function localizedPostBuilderCopy(): PostBuilderCopy {
	return {
		pageTitle: m.post_builder_page_title(),
		pageDescription: m.post_builder_page_description(),
		builderMode: m.post_builder_mode_builder(),
		manualMode: m.post_builder_mode_manual(),
		creationModeLabel: m.post_builder_creation_mode_label(),
		builderInputModeLabel: m.post_builder_input_mode_label(),
		fromSourceMode: m.post_builder_mode_source(),
		discoverMode: m.post_builder_mode_discover(),
		builderInputHeading: m.post_builder_input_heading(),
		builderInputDescription: m.post_builder_input_description(),
		sourcePlaceholder: m.post_builder_source_placeholder(),
		attach: m.post_builder_attach(),
		pasteLink: m.post_builder_paste_link(),
		record: m.post_builder_record(),
		addContext: m.post_builder_add_context(),
		removeSource: m.post_builder_remove_source(),
		sourceMaterialLabel: m.post_builder_source_material(),
		voice: m.post_builder_voice(),
		destinations: m.post_builder_destinations(),
		direction: m.post_builder_direction(),
		buildPost: m.post_builder_build_post(),
		buildOpportunity: m.post_builder_build_opportunity(),
		buildingPost: m.post_builder_building_post(),
		privacyNote: m.post_builder_privacy_note(),
		whatHappensHeading: m.post_builder_steps_heading(),
		whatHappensSteps: [
			m.post_builder_step_angle(),
			m.post_builder_step_destinations(),
			m.post_builder_step_media(),
			m.post_builder_step_composer()
		],
		inspirationHeading: m.post_builder_inspiration_heading(),
		inspirationDescription: m.post_builder_inspiration_description(),
		loadMoreIdeas: m.post_builder_load_more_ideas(),
		discoverHeading: m.post_builder_discover_heading(),
		discoverDescription: m.post_builder_discover_description(),
		discoverEmptyTitle: m.post_builder_discover_empty_title(),
		discoverEmptyDescription: m.post_builder_discover_empty_description(),
		refreshDiscover: m.post_builder_refresh_discover(),
		loadMoreOpportunities: m.post_builder_load_more_opportunities(),
		loadingOpportunities: m.post_builder_loading_opportunities(),
		whyThisFits: m.post_builder_why_this_fits(),
		possibleAngles: m.post_builder_possible_angles(),
		chooseAngle: m.post_builder_choose_angle(),
		selectedAngle: m.post_builder_selected_angle(),
		recommendedTreatment: m.post_builder_recommended_treatment(),
		selectOpportunity: m.post_builder_select_opportunity(),
		selectedOpportunity: m.post_builder_selected_opportunity(),
		buildProgressHeading: m.post_builder_progress_heading(),
		reviewingDraft: m.post_builder_reviewing_draft(),
		buildCancelled: m.post_builder_cancelled(),
		cancelBuild: m.common_cancel(),
		retryBuild: m.common_retry(),
		resultHeading: m.post_builder_result_heading(),
		resultDescription: m.post_builder_result_description(),
		coreThesis: m.post_builder_core_thesis(),
		reviewInComposer: m.post_builder_review_in_composer(),
		openingComposer: m.post_builder_opening_composer(),
		buildAnother: m.post_builder_build_another(),
		angle: m.post_builder_angle(),
		goal: m.post_builder_goal(),
		audience: m.post_builder_audience(),
		voiceUsed: m.post_builder_voice(),
		destinationPlan: m.post_builder_destination_plan(),
		claimReview: m.post_builder_claim_review(),
		mediaPlan: m.post_builder_media_plan(),
		makeMeme: m.post_builder_make_meme(),
		createVisual: m.post_builder_create_visual(),
		annotateSource: m.post_builder_annotate_source(),
		createVideo: m.post_builder_create_video(),
		editVideo: m.post_builder_edit_video(),
		preparingMedia: m.post_builder_preparing_media(),
		evidenceOnly: m.post_builder_evidence_only(),
		mayPublish: m.post_builder_may_publish(),
		included: m.post_builder_included(),
		skipped: m.post_builder_skipped(),
		needsReview: m.post_builder_needs_review(),
		supported: m.post_builder_verified(),
		userAsserted: m.post_builder_context_user_asserted(),
		opinion: m.post_builder_context_opinion(),
		parody: m.post_builder_context_parody(),
		needsVerification: m.post_builder_context_needs_verification(),
		noClaimsNeedReview: m.post_builder_no_claims_review(),
		workspaceRequired: m.post_builder_workspace_required(),
		sourceRequired: m.post_builder_source_required(),
		opportunityRequired: m.post_builder_opportunity_required(),
		destinationsRequired: m.post_builder_destinations_required(),
		requestFailed: m.post_builder_request_failed(),
		dismissError: m.post_builder_dismiss_error(),
		builderHelpLabel: m.post_builder_help_label(),
		footerNote: m.post_builder_footer_note()
	};
}
