// Generated from backend/internal/services/themes/builtins.v1.json. Do not edit by hand.
import type { NativeThemeFamily } from "./contract";

export const GENERATED_BUILTIN_THEME_IDS = [
  "workshop",
  "studio",
  "notebook",
  "playroom",
  "cloud-garden",
  "study-hall",
  "corkboard",
  "midnight",
] as const;

export const GENERATED_BUILTIN_THEME_FAMILIES = {
  workshop: {
    id: "workshop",
    displayName: "Workshop",
    revision: "builtin-v1",
    supportedSchemes: ["light", "dark"],
    manifests: {
      light: {
        id: "workshop-light-builtin-v1",
        familyId: "workshop",
        displayName: "Workshop",
        scheme: "light",
        colors: {
          background: "#fbfaf9ff",
          surface: "#ffffffff",
          surfaceContainer: "#efeeecff",
          surfaceContainerHigh: "#ffffffff",
          onSurface: "#1a1512ff",
          onSurfaceVariant: "#706761ff",
          outline: "#e0dedaff",
          outlineVariant: "#e0dedaff",
          primary: "#b74c05ff",
          onPrimary: "#fbfaf9ff",
          primaryContainer: "#ffe0d2ff",
          onPrimaryContainer: "#211914ff",
          secondaryContainer: "#ffe0d2ff",
          onSecondaryContainer: "#211914ff",
          error: "#db1a2bff",
          onError: "#fafafaff",
          errorContainer: "#db1a2b1f",
          onErrorContainer: "#a20003ff",
          success: "#d3ecdbff",
          onSuccess: "#00572dff",
          warning: "#ffe8c2ff",
          onWarning: "#704000ff",
          link: "#b74c05ff",
          focus: "#1a1512ff",
          scrim: "#1a151285",
          shadow: "#1a1512ff",
          status: {
            draft: "#706761ff",
            ready: "#004b83ff",
            scheduled: "#704000ff",
            publishing: "#b74c05ff",
            published: "#00572dff",
            failed: "#db1a2bff",
          },
        },
        actions: {
          focal: {
            border: "#b74c05ff",
            borderWidth: 1,
            container: "#b74c05ff",
            content: "#fbfaf9ff",
            pressedContainer: "#98430fff",
            pressedContent: "#fbfaf9ff",
            depthColor: "#1a1512ff",
            depth: 5,
            disabledOpacity: 0.42,
            underline: false,
          },
          primary: {
            border: "#241e1aff",
            borderWidth: 1,
            container: "#241e1aff",
            content: "#fbfaf9ff",
            pressedContainer: "#0d0806ff",
            pressedContent: "#fbfaf9ff",
            depthColor: "#00000000",
            depth: 0,
            disabledOpacity: 0.42,
            underline: false,
          },
          ordinary: {
            border: "#e0dedaff",
            borderWidth: 1,
            container: "#f3f2eeff",
            content: "#26201dff",
            pressedContainer: "#c7c5c1ff",
            pressedContent: "#26201dff",
            depthColor: "#00000000",
            depth: 0,
            disabledOpacity: 0.42,
            underline: false,
          },
          quiet: {
            border: "#00000000",
            borderWidth: 0,
            container: "#00000000",
            content: "#1a1512ff",
            pressedContainer: "#ceccc9ff",
            pressedContent: "#1a1512ff",
            depthColor: "#00000000",
            depth: 0,
            disabledOpacity: 0.42,
            underline: false,
          },
          destructive: {
            border: "#00000000",
            borderWidth: 0,
            container: "#db1a2b1f",
            content: "#a20003ff",
            pressedContainer: "#db1a2b47",
            pressedContent: "#a20003ff",
            depthColor: "#00000000",
            depth: 0,
            disabledOpacity: 0.42,
            underline: false,
          },
          link: {
            border: "#00000000",
            borderWidth: 0,
            container: "#00000000",
            content: "#b74c05ff",
            pressedContainer: "#00000000",
            pressedContent: "#98430fff",
            depthColor: "#00000000",
            depth: 0,
            disabledOpacity: 0.42,
            underline: true,
          },
        },
        editor: {
          canvas: "#0d0b09ff",
          canvasGrid: "#2d2824ff",
          canvasSelection: "#d86d38ff",
          canvasSelectionText: "#ecebe8ff",
          transparencyLight: "#070504ff",
          transparencyDark: "#0d0b09ff",
          timeline: "#191513ff",
          timelineTrack: "#14110eff",
          timelinePlayhead: "#d86d38ff",
          waveform: "#96aec3ff",
          handle: "#f8f8f8ff",
          safeArea: "#a8bacab8",
          mediaScrim: "#1a151285",
        },
        typography: {
          displayLarge: {
            fontSize: 32,
            fontWeight: "600",
            letterSpacing: -1.12,
            lineHeight: 33.6,
          },
          headlineLarge: {
            fontSize: 24,
            fontWeight: "600",
            letterSpacing: -0.6,
            lineHeight: 27.6,
          },
          titleLarge: {
            fontSize: 24,
            fontWeight: "600",
            letterSpacing: -0.6,
            lineHeight: 27.6,
          },
          titleMedium: {
            fontSize: 13,
            fontWeight: "600",
            letterSpacing: 0,
            lineHeight: 16.25,
          },
          bodyLarge: {
            fontSize: 14,
            fontWeight: "400",
            letterSpacing: 0,
            lineHeight: 21,
          },
          bodyMedium: {
            fontSize: 14,
            fontWeight: "400",
            letterSpacing: 0,
            lineHeight: 21,
          },
          bodySmall: {
            fontSize: 12,
            fontWeight: "500",
            letterSpacing: 0.18,
            lineHeight: 16.2,
          },
          labelLarge: {
            fontSize: 13,
            fontWeight: "600",
            letterSpacing: 0,
            lineHeight: 16.25,
          },
          labelMedium: {
            fontSize: 12,
            fontWeight: "500",
            letterSpacing: 0.18,
            lineHeight: 16.2,
          },
        },
        shape: {
          extraSmall: 8,
          small: 8,
          medium: 10,
          large: 12,
          extraLarge: 14,
          full: 999,
        },
        spacing: {
          extraSmall: 4,
          small: 8,
          medium: 12,
          large: 16,
          extraLarge: 24,
          doubleExtraLarge: 36,
        },
        motion: {
          quickMs: 100,
          standardMs: 160,
          emphasizedMs: 240,
        },
        shell: {
          contentMaxWidth: 1152,
          sidebarWidth: 256,
          headerHeight: 56,
          mobileNavigationHeight: 72,
          canvasTreatment: "plain",
        },
        components: {
          button: "solid",
          link: "underlined",
          tabs: "underline",
          navigation: "quiet",
          input: "outlined",
          select: "outlined",
          card: "outlined",
          container: "flat",
          table: "ruled",
          list: "divided",
          badge: "tonal",
          chip: "tonal",
          dialog: "elevated",
          popover: "elevated",
          toast: "outlined",
          switch: "solid",
          checkbox: "solid",
          radio: "solid",
          toolbar: "flat",
          pagination: "quiet",
          emptyState: "plain",
          loadingState: "skeleton",
          editorChrome: "neutral",
          decoration: "none",
        },
        assetSlots: {},
        decoration: {
          celebration: ["#c44c00ff", "#00845dff", "#2274afff", "#b27f02ff", "#894d97ff"],
        },
        iconography: {
          packId: "lucide",
          roles: {
            add: "plus",
            back: "arrow-left",
            next: "arrow-right",
            disclosure: "chevron-right",
            close: "x",
            menu: "menu",
            more: "ellipsis",
            search: "search",
            settings: "settings",
            edit: "pencil",
            delete: "trash-2",
            check: "check",
            retry: "rotate-cw",
            calendar: "calendar-days",
            queue: "list-clock",
            drafts: "file-pen-line",
            workspace: "panels-top-left",
            link: "external-link",
            account: "circle-user-round",
            notification: "bell",
            undo: "undo-2",
            redo: "redo-2",
          },
        },
      },
      dark: {
        id: "workshop-dark-builtin-v1",
        familyId: "workshop",
        displayName: "Workshop",
        scheme: "dark",
        colors: {
          background: "#0d0907ff",
          surface: "#1a1512ff",
          surfaceContainer: "#15100dff",
          surfaceContainerHigh: "#1f1916ff",
          onSurface: "#e6e4e1ff",
          onSurfaceVariant: "#9d938dff",
          outline: "#2c2520ff",
          outlineVariant: "#2c2520ff",
          primary: "#d77343ff",
          onPrimary: "#080503ff",
          primaryContainer: "#4e2714ff",
          onPrimaryContainer: "#f1eae0ff",
          secondaryContainer: "#4e2714ff",
          onSecondaryContainer: "#f1eae0ff",
          error: "#f05653ff",
          onError: "#080503ff",
          errorContainer: "#f056531f",
          onErrorContainer: "#ffaea5ff",
          success: "#12301eff",
          onSuccess: "#73ce95ff",
          warning: "#3b2700ff",
          onWarning: "#edbb64ff",
          link: "#d77343ff",
          focus: "#e6e4e1ff",
          scrim: "#e6e4e185",
          shadow: "#e6e4e1ff",
          status: {
            draft: "#9d938dff",
            ready: "#72b8f2ff",
            scheduled: "#edbb64ff",
            publishing: "#d77343ff",
            published: "#73ce95ff",
            failed: "#f05653ff",
          },
        },
        actions: {
          focal: {
            border: "#d77343ff",
            borderWidth: 1,
            container: "#d77343ff",
            content: "#080503ff",
            pressedContainer: "#d98b59ff",
            pressedContent: "#080503ff",
            depthColor: "#e6e4e1ff",
            depth: 5,
            disabledOpacity: 0.42,
            underline: false,
          },
          primary: {
            border: "#e0dedaff",
            borderWidth: 1,
            container: "#e0dedaff",
            content: "#110c09ff",
            pressedContainer: "#f9f8f6ff",
            pressedContent: "#110c09ff",
            depthColor: "#00000000",
            depth: 0,
            disabledOpacity: 0.42,
            underline: false,
          },
          ordinary: {
            border: "#2c2520ff",
            borderWidth: 1,
            container: "#27201aff",
            content: "#dfdedaff",
            pressedContainer: "#0e0a08ff",
            pressedContent: "#dfdedaff",
            depthColor: "#00000000",
            depth: 0,
            disabledOpacity: 0.42,
            underline: false,
          },
          quiet: {
            border: "#00000000",
            borderWidth: 0,
            container: "#00000000",
            content: "#e6e4e1ff",
            pressedContainer: "#2d2925ff",
            pressedContent: "#e6e4e1ff",
            depthColor: "#00000000",
            depth: 0,
            disabledOpacity: 0.42,
            underline: false,
          },
          destructive: {
            border: "#00000000",
            borderWidth: 0,
            container: "#f056531f",
            content: "#ffaea5ff",
            pressedContainer: "#f0565347",
            pressedContent: "#ffaea5ff",
            depthColor: "#00000000",
            depth: 0,
            disabledOpacity: 0.42,
            underline: false,
          },
          link: {
            border: "#00000000",
            borderWidth: 0,
            container: "#00000000",
            content: "#d77343ff",
            pressedContainer: "#00000000",
            pressedContent: "#d98b59ff",
            depthColor: "#00000000",
            depth: 0,
            disabledOpacity: 0.42,
            underline: true,
          },
        },
        editor: {
          canvas: "#070504ff",
          canvasGrid: "#26201dff",
          canvasSelection: "#f47f46ff",
          canvasSelectionText: "#ecebe8ff",
          transparencyLight: "#040302ff",
          transparencyDark: "#070504ff",
          timeline: "#14110eff",
          timelineTrack: "#100c0aff",
          timelinePlayhead: "#f47f46ff",
          waveform: "#9db4c9ff",
          handle: "#f8f8f8ff",
          safeArea: "#aec0d0b8",
          mediaScrim: "#e6e4e185",
        },
        typography: {
          displayLarge: {
            fontSize: 32,
            fontWeight: "600",
            letterSpacing: -1.12,
            lineHeight: 33.6,
          },
          headlineLarge: {
            fontSize: 24,
            fontWeight: "600",
            letterSpacing: -0.6,
            lineHeight: 27.6,
          },
          titleLarge: {
            fontSize: 24,
            fontWeight: "600",
            letterSpacing: -0.6,
            lineHeight: 27.6,
          },
          titleMedium: {
            fontSize: 13,
            fontWeight: "600",
            letterSpacing: 0,
            lineHeight: 16.25,
          },
          bodyLarge: {
            fontSize: 14,
            fontWeight: "400",
            letterSpacing: 0,
            lineHeight: 21,
          },
          bodyMedium: {
            fontSize: 14,
            fontWeight: "400",
            letterSpacing: 0,
            lineHeight: 21,
          },
          bodySmall: {
            fontSize: 12,
            fontWeight: "500",
            letterSpacing: 0.18,
            lineHeight: 16.2,
          },
          labelLarge: {
            fontSize: 13,
            fontWeight: "600",
            letterSpacing: 0,
            lineHeight: 16.25,
          },
          labelMedium: {
            fontSize: 12,
            fontWeight: "500",
            letterSpacing: 0.18,
            lineHeight: 16.2,
          },
        },
        shape: {
          extraSmall: 8,
          small: 8,
          medium: 10,
          large: 12,
          extraLarge: 14,
          full: 999,
        },
        spacing: {
          extraSmall: 4,
          small: 8,
          medium: 12,
          large: 16,
          extraLarge: 24,
          doubleExtraLarge: 36,
        },
        motion: {
          quickMs: 100,
          standardMs: 160,
          emphasizedMs: 240,
        },
        shell: {
          contentMaxWidth: 1152,
          sidebarWidth: 256,
          headerHeight: 56,
          mobileNavigationHeight: 72,
          canvasTreatment: "plain",
        },
        components: {
          button: "solid",
          link: "underlined",
          tabs: "underline",
          navigation: "quiet",
          input: "outlined",
          select: "outlined",
          card: "outlined",
          container: "flat",
          table: "ruled",
          list: "divided",
          badge: "tonal",
          chip: "tonal",
          dialog: "elevated",
          popover: "elevated",
          toast: "outlined",
          switch: "solid",
          checkbox: "solid",
          radio: "solid",
          toolbar: "flat",
          pagination: "quiet",
          emptyState: "plain",
          loadingState: "skeleton",
          editorChrome: "neutral",
          decoration: "none",
        },
        assetSlots: {},
        decoration: {
          celebration: ["#e37035ff", "#42b389ff", "#519fddff", "#cf9a35ff", "#b576c3ff"],
        },
        iconography: {
          packId: "lucide",
          roles: {
            add: "plus",
            back: "arrow-left",
            next: "arrow-right",
            disclosure: "chevron-right",
            close: "x",
            menu: "menu",
            more: "ellipsis",
            search: "search",
            settings: "settings",
            edit: "pencil",
            delete: "trash-2",
            check: "check",
            retry: "rotate-cw",
            calendar: "calendar-days",
            queue: "list-clock",
            drafts: "file-pen-line",
            workspace: "panels-top-left",
            link: "external-link",
            account: "circle-user-round",
            notification: "bell",
            undo: "undo-2",
            redo: "redo-2",
          },
        },
      },
    },
  },
  studio: {
    id: "studio",
    displayName: "Studio",
    revision: "builtin-v1",
    supportedSchemes: ["light"],
    manifests: {
      light: {
        id: "studio-light-builtin-v1",
        familyId: "studio",
        displayName: "Studio",
        scheme: "light",
        colors: {
          background: "#fafcfeff",
          surface: "#ffffffff",
          surfaceContainer: "#eef2f7ff",
          surfaceContainerHigh: "#ffffffff",
          onSurface: "#0d1218ff",
          onSurfaceVariant: "#5a6472ff",
          outline: "#d8dfe6ff",
          outlineVariant: "#d8dfe6ff",
          primary: "#0063d7ff",
          onPrimary: "#fafcfeff",
          primaryContainer: "#c6e5ffff",
          onPrimaryContainer: "#001c41ff",
          secondaryContainer: "#c6e5ffff",
          onSecondaryContainer: "#001c41ff",
          error: "#d81327ff",
          onError: "#fcfcfcff",
          errorContainer: "#d813271f",
          onErrorContainer: "#a20003ff",
          success: "#d4f0dcff",
          onSuccess: "#005520ff",
          warning: "#ffecc5ff",
          onWarning: "#6f4600ff",
          link: "#0063d7ff",
          focus: "#0d1218ff",
          scrim: "#0d121885",
          shadow: "#0d1218ff",
          status: {
            draft: "#5a6472ff",
            ready: "#0049a1ff",
            scheduled: "#6f4600ff",
            publishing: "#0063d7ff",
            published: "#005520ff",
            failed: "#d81327ff",
          },
        },
        actions: {
          focal: {
            border: "#0063d7ff",
            borderWidth: 1,
            container: "#0063d7ff",
            content: "#fafcfeff",
            pressedContainer: "#0054b1ff",
            pressedContent: "#fafcfeff",
            depthColor: "#0d1218ff",
            depth: 5,
            disabledOpacity: 0.42,
            underline: false,
          },
          primary: {
            border: "#10171fff",
            borderWidth: 1,
            container: "#10171fff",
            content: "#fcfcfcff",
            pressedContainer: "#020306ff",
            pressedContent: "#fcfcfcff",
            depthColor: "#00000000",
            depth: 0,
            disabledOpacity: 0.42,
            underline: false,
          },
          ordinary: {
            border: "#d8dfe6ff",
            borderWidth: 1,
            container: "#ebf3fbff",
            content: "#131e2bff",
            pressedContainer: "#bdc5cdff",
            pressedContent: "#131e2bff",
            depthColor: "#00000000",
            depth: 0,
            disabledOpacity: 0.42,
            underline: false,
          },
          quiet: {
            border: "#00000000",
            borderWidth: 0,
            container: "#00000000",
            content: "#0d1218ff",
            pressedContainer: "#caced4ff",
            pressedContent: "#0d1218ff",
            depthColor: "#00000000",
            depth: 0,
            disabledOpacity: 0.42,
            underline: false,
          },
          destructive: {
            border: "#00000000",
            borderWidth: 0,
            container: "#d813271f",
            content: "#a20003ff",
            pressedContainer: "#d8132747",
            pressedContent: "#a20003ff",
            depthColor: "#00000000",
            depth: 0,
            disabledOpacity: 0.42,
            underline: false,
          },
          link: {
            border: "#00000000",
            borderWidth: 0,
            container: "#00000000",
            content: "#0063d7ff",
            pressedContainer: "#00000000",
            pressedContent: "#0054b1ff",
            depthColor: "#00000000",
            depth: 0,
            disabledOpacity: 0.42,
            underline: true,
          },
        },
        editor: {
          canvas: "#0d0b09ff",
          canvasGrid: "#2d2824ff",
          canvasSelection: "#d86d38ff",
          canvasSelectionText: "#ecebe8ff",
          transparencyLight: "#070504ff",
          transparencyDark: "#0d0b09ff",
          timeline: "#191513ff",
          timelineTrack: "#14110eff",
          timelinePlayhead: "#d86d38ff",
          waveform: "#96aec3ff",
          handle: "#f8f8f8ff",
          safeArea: "#a8bacab8",
          mediaScrim: "#0d121885",
        },
        typography: {
          displayLarge: {
            fontSize: 32,
            fontWeight: "600",
            letterSpacing: -1.12,
            lineHeight: 33.6,
          },
          headlineLarge: {
            fontSize: 24,
            fontWeight: "600",
            letterSpacing: -0.6,
            lineHeight: 27.6,
          },
          titleLarge: {
            fontSize: 24,
            fontWeight: "600",
            letterSpacing: -0.6,
            lineHeight: 27.6,
          },
          titleMedium: {
            fontSize: 13,
            fontWeight: "600",
            letterSpacing: 0,
            lineHeight: 16.25,
          },
          bodyLarge: {
            fontSize: 14,
            fontWeight: "400",
            letterSpacing: 0,
            lineHeight: 21,
          },
          bodyMedium: {
            fontSize: 14,
            fontWeight: "400",
            letterSpacing: 0,
            lineHeight: 21,
          },
          bodySmall: {
            fontSize: 12,
            fontWeight: "500",
            letterSpacing: 0.18,
            lineHeight: 16.2,
          },
          labelLarge: {
            fontSize: 13,
            fontWeight: "600",
            letterSpacing: 0,
            lineHeight: 16.25,
          },
          labelMedium: {
            fontSize: 12,
            fontWeight: "500",
            letterSpacing: 0.18,
            lineHeight: 16.2,
          },
        },
        shape: {
          extraSmall: 8,
          small: 8,
          medium: 12,
          large: 14,
          extraLarge: 14,
          full: 999,
        },
        spacing: {
          extraSmall: 4,
          small: 8,
          medium: 12,
          large: 16,
          extraLarge: 24,
          doubleExtraLarge: 36,
        },
        motion: {
          quickMs: 100,
          standardMs: 160,
          emphasizedMs: 240,
        },
        shell: {
          contentMaxWidth: 1152,
          sidebarWidth: 256,
          headerHeight: 56,
          mobileNavigationHeight: 72,
          canvasTreatment: "plain",
        },
        components: {
          button: "solid",
          link: "underlined",
          tabs: "underline",
          navigation: "quiet",
          input: "outlined",
          select: "outlined",
          card: "flat",
          container: "flat",
          table: "ruled",
          list: "divided",
          badge: "tonal",
          chip: "tonal",
          dialog: "elevated",
          popover: "elevated",
          toast: "outlined",
          switch: "solid",
          checkbox: "solid",
          radio: "solid",
          toolbar: "flat",
          pagination: "quiet",
          emptyState: "plain",
          loadingState: "skeleton",
          editorChrome: "neutral",
          decoration: "none",
        },
        assetSlots: {},
        decoration: {
          celebration: ["#0070e5ff", "#0091a4ff", "#966cd7ff", "#ca8500ff", "#14874eff"],
        },
        iconography: {
          packId: "heroicons-outline",
          roles: {
            add: "plus-circle",
            back: "arrow-long-left",
            next: "arrow-long-right",
            disclosure: "chevron-double-right",
            close: "x-circle",
            menu: "bars-3-bottom-left",
            more: "ellipsis-horizontal-circle",
            search: "magnifying-glass-circle",
            settings: "cog-6-tooth",
            edit: "pencil-square",
            delete: "trash",
            check: "check-circle",
            retry: "arrow-path-rounded-square",
            calendar: "calendar-date-range",
            queue: "queue-list",
            drafts: "document-text",
            workspace: "squares-2x2",
            link: "arrow-top-right-on-square",
            account: "user-circle",
            notification: "bell-alert",
            undo: "arrow-uturn-left",
            redo: "arrow-uturn-right",
          },
        },
      },
    },
  },
  notebook: {
    id: "notebook",
    displayName: "Notebook",
    revision: "builtin-v1",
    supportedSchemes: ["light"],
    manifests: {
      light: {
        id: "notebook-light-builtin-v1",
        familyId: "notebook",
        displayName: "Notebook",
        scheme: "light",
        colors: {
          background: "#fdf6eaff",
          surface: "#fffdf5ff",
          surfaceContainer: "#f5ead7ff",
          surfaceContainerHigh: "#fffdf5ff",
          onSurface: "#281d13ff",
          onSurfaceVariant: "#72604aff",
          outline: "#ddcfb8ff",
          outlineVariant: "#ddcfb8ff",
          primary: "#dea143ff",
          onPrimary: "#190f06ff",
          primaryContainer: "#c2e4f8ff",
          onPrimaryContainer: "#00273eff",
          secondaryContainer: "#c2e4f8ff",
          onSecondaryContainer: "#00273eff",
          error: "#c53829ff",
          onError: "#fffbf4ff",
          errorContainer: "#c538291f",
          onErrorContainer: "#a20003ff",
          success: "#cae7caff",
          onSuccess: "#17501dff",
          warning: "#ffdbaaff",
          onWarning: "#6d3900ff",
          link: "#076798ff",
          focus: "#281d13ff",
          scrim: "#281d1385",
          shadow: "#281d13ff",
          status: {
            draft: "#72604aff",
            ready: "#004776ff",
            scheduled: "#6d3900ff",
            publishing: "#936a2fff",
            published: "#17501dff",
            failed: "#c53829ff",
          },
        },
        actions: {
          focal: {
            border: "#dea143ff",
            borderWidth: 1,
            container: "#dea143ff",
            content: "#190f06ff",
            pressedContainer: "#ba863cff",
            pressedContent: "#190f06ff",
            depthColor: "#281d13ff",
            depth: 5,
            disabledOpacity: 0.42,
            underline: false,
          },
          primary: {
            border: "#352516ff",
            borderWidth: 1,
            container: "#352516ff",
            content: "#fffbf4ff",
            pressedContainer: "#130b05ff",
            pressedContent: "#fffbf4ff",
            depthColor: "#00000000",
            depth: 0,
            disabledOpacity: 0.42,
            underline: false,
          },
          ordinary: {
            border: "#ddcfb8ff",
            borderWidth: 1,
            container: "#f4e6ceff",
            content: "#352516ff",
            pressedContainer: "#cbbea8ff",
            pressedContent: "#352516ff",
            depthColor: "#00000000",
            depth: 0,
            disabledOpacity: 0.42,
            underline: false,
          },
          quiet: {
            border: "#00000000",
            borderWidth: 0,
            container: "#00000000",
            content: "#281d13ff",
            pressedContainer: "#d5cab8ff",
            pressedContent: "#281d13ff",
            depthColor: "#00000000",
            depth: 0,
            disabledOpacity: 0.42,
            underline: false,
          },
          destructive: {
            border: "#00000000",
            borderWidth: 0,
            container: "#c538291f",
            content: "#a20003ff",
            pressedContainer: "#c5382947",
            pressedContent: "#a20003ff",
            depthColor: "#00000000",
            depth: 0,
            disabledOpacity: 0.42,
            underline: false,
          },
          link: {
            border: "#00000000",
            borderWidth: 0,
            container: "#00000000",
            content: "#076798ff",
            pressedContainer: "#00000000",
            pressedContent: "#00616fff",
            depthColor: "#00000000",
            depth: 0,
            disabledOpacity: 0.42,
            underline: true,
          },
        },
        editor: {
          canvas: "#0d0b09ff",
          canvasGrid: "#2d2824ff",
          canvasSelection: "#d86d38ff",
          canvasSelectionText: "#ecebe8ff",
          transparencyLight: "#070504ff",
          transparencyDark: "#0d0b09ff",
          timeline: "#191513ff",
          timelineTrack: "#14110eff",
          timelinePlayhead: "#d86d38ff",
          waveform: "#96aec3ff",
          handle: "#f8f8f8ff",
          safeArea: "#a8bacab8",
          mediaScrim: "#281d1385",
        },
        typography: {
          displayLarge: {
            fontSize: 32,
            fontWeight: "600",
            letterSpacing: -0.576,
            lineHeight: 33.6,
          },
          headlineLarge: {
            fontSize: 24,
            fontWeight: "600",
            letterSpacing: -0.432,
            lineHeight: 27.6,
          },
          titleLarge: {
            fontSize: 24,
            fontWeight: "600",
            letterSpacing: -0.432,
            lineHeight: 27.6,
          },
          titleMedium: {
            fontSize: 13,
            fontWeight: "600",
            letterSpacing: 0,
            lineHeight: 16.25,
          },
          bodyLarge: {
            fontSize: 14,
            fontWeight: "400",
            letterSpacing: 0,
            lineHeight: 21,
          },
          bodyMedium: {
            fontSize: 14,
            fontWeight: "400",
            letterSpacing: 0,
            lineHeight: 21,
          },
          bodySmall: {
            fontSize: 12,
            fontWeight: "500",
            letterSpacing: 0.18,
            lineHeight: 16.2,
          },
          labelLarge: {
            fontSize: 13,
            fontWeight: "600",
            letterSpacing: 0,
            lineHeight: 16.25,
          },
          labelMedium: {
            fontSize: 12,
            fontWeight: "500",
            letterSpacing: 0.18,
            lineHeight: 16.2,
          },
        },
        shape: {
          extraSmall: 8,
          small: 8,
          medium: 8,
          large: 10,
          extraLarge: 14,
          full: 999,
        },
        spacing: {
          extraSmall: 4,
          small: 8,
          medium: 12,
          large: 16,
          extraLarge: 28,
          doubleExtraLarge: 40,
        },
        motion: {
          quickMs: 100,
          standardMs: 160,
          emphasizedMs: 240,
        },
        shell: {
          contentMaxWidth: 1152,
          sidebarWidth: 256,
          headerHeight: 56,
          mobileNavigationHeight: 72,
          canvasTreatment: "paper",
        },
        components: {
          button: "solid",
          link: "underlined",
          tabs: "underline",
          navigation: "quiet",
          input: "underlined",
          select: "underlined",
          card: "paper",
          container: "tinted",
          table: "ruled",
          list: "divided",
          badge: "tonal",
          chip: "tonal",
          dialog: "elevated",
          popover: "elevated",
          toast: "outlined",
          switch: "solid",
          checkbox: "solid",
          radio: "solid",
          toolbar: "flat",
          pagination: "quiet",
          emptyState: "plain",
          loadingState: "skeleton",
          editorChrome: "neutral",
          decoration: "editorial",
        },
        assetSlots: {},
        decoration: {
          celebration: ["#b16600ff", "#c25d58ff", "#2181afff", "#349d62ff", "#8a5c9dff"],
        },
        iconography: {
          packId: "tabler",
          roles: {
            add: "square-rounded-plus",
            back: "arrow-back-up",
            next: "arrow-forward-up",
            disclosure: "chevron-right",
            close: "square-rounded-x",
            menu: "menu-2",
            more: "dots-circle-horizontal",
            search: "zoom",
            settings: "adjustments-horizontal",
            edit: "edit-circle",
            delete: "trash-x",
            check: "checkbox",
            retry: "refresh-alert",
            calendar: "calendar-event",
            queue: "checklist",
            drafts: "note",
            workspace: "layout-dashboard",
            link: "external-link",
            account: "user-square-rounded",
            notification: "bell-ringing-2",
            undo: "corner-up-left",
            redo: "corner-up-right",
          },
        },
      },
    },
  },
  playroom: {
    id: "playroom",
    displayName: "Playroom",
    revision: "builtin-v1",
    supportedSchemes: ["light"],
    manifests: {
      light: {
        id: "playroom-light-builtin-v1",
        familyId: "playroom",
        displayName: "Playroom",
        scheme: "light",
        colors: {
          background: "#fcfaf3ff",
          surface: "#ffffffff",
          surfaceContainer: "#f5efd8ff",
          surfaceContainerHigh: "#ffffffff",
          onSurface: "#131a2bff",
          onSurfaceVariant: "#515d78ff",
          outline: "#252e40ff",
          outlineVariant: "#252e40ff",
          primary: "#009824ff",
          onPrimary: "#001201ff",
          primaryContainer: "#c7edc7ff",
          onPrimaryContainer: "#002e02ff",
          secondaryContainer: "#c7edc7ff",
          onSecondaryContainer: "#002e02ff",
          error: "#df202eff",
          onError: "#fcfcfcff",
          errorContainer: "#df202e1f",
          onErrorContainer: "#a20003ff",
          success: "#c2ebc2ff",
          onSuccess: "#004700ff",
          warning: "#ffe096ff",
          onWarning: "#6f3800ff",
          link: "#005ecbff",
          focus: "#131a2bff",
          scrim: "#131a2b85",
          shadow: "#131a2bff",
          status: {
            draft: "#515d78ff",
            ready: "#003d94ff",
            scheduled: "#6f3800ff",
            publishing: "#038625ff",
            published: "#004700ff",
            failed: "#df202eff",
          },
        },
        actions: {
          focal: {
            border: "#009824ff",
            borderWidth: 2,
            container: "#009824ff",
            content: "#001201ff",
            pressedContainer: "#5ec165ff",
            pressedContent: "#001201ff",
            depthColor: "#131a2bff",
            depth: 5,
            disabledOpacity: 0.42,
            underline: false,
          },
          primary: {
            border: "#161f32ff",
            borderWidth: 2,
            container: "#161f32ff",
            content: "#fcfcfcff",
            pressedContainer: "#03050fff",
            pressedContent: "#fcfcfcff",
            depthColor: "#00000000",
            depth: 0,
            disabledOpacity: 0.42,
            underline: false,
          },
          ordinary: {
            border: "#252e40ff",
            borderWidth: 2,
            container: "#f4eccaff",
            content: "#161f32ff",
            pressedContainer: "#bac6a9ff",
            pressedContent: "#161f32ff",
            depthColor: "#00000000",
            depth: 0,
            disabledOpacity: 0.42,
            underline: false,
          },
          quiet: {
            border: "#00000000",
            borderWidth: 0,
            container: "#00000000",
            content: "#131a2bff",
            pressedContainer: "#cbd0baff",
            pressedContent: "#131a2bff",
            depthColor: "#00000000",
            depth: 0,
            disabledOpacity: 0.42,
            underline: false,
          },
          destructive: {
            border: "#00000000",
            borderWidth: 0,
            container: "#df202e1f",
            content: "#a20003ff",
            pressedContainer: "#df202e47",
            pressedContent: "#a20003ff",
            depthColor: "#00000000",
            depth: 0,
            disabledOpacity: 0.42,
            underline: false,
          },
          link: {
            border: "#00000000",
            borderWidth: 0,
            container: "#00000000",
            content: "#005ecbff",
            pressedContainer: "#00000000",
            pressedContent: "#0051acff",
            depthColor: "#00000000",
            depth: 0,
            disabledOpacity: 0.42,
            underline: true,
          },
        },
        editor: {
          canvas: "#0d0b09ff",
          canvasGrid: "#2d2824ff",
          canvasSelection: "#d86d38ff",
          canvasSelectionText: "#ecebe8ff",
          transparencyLight: "#070504ff",
          transparencyDark: "#0d0b09ff",
          timeline: "#191513ff",
          timelineTrack: "#14110eff",
          timelinePlayhead: "#d86d38ff",
          waveform: "#96aec3ff",
          handle: "#f8f8f8ff",
          safeArea: "#a8bacab8",
          mediaScrim: "#131a2b85",
        },
        typography: {
          displayLarge: {
            fontSize: 32,
            fontWeight: "700",
            letterSpacing: -1.12,
            lineHeight: 33.6,
          },
          headlineLarge: {
            fontSize: 24,
            fontWeight: "700",
            letterSpacing: -0.6,
            lineHeight: 27.6,
          },
          titleLarge: {
            fontSize: 24,
            fontWeight: "700",
            letterSpacing: -0.6,
            lineHeight: 27.6,
          },
          titleMedium: {
            fontSize: 13,
            fontWeight: "600",
            letterSpacing: 0,
            lineHeight: 16.25,
          },
          bodyLarge: {
            fontSize: 14,
            fontWeight: "400",
            letterSpacing: 0,
            lineHeight: 21,
          },
          bodyMedium: {
            fontSize: 14,
            fontWeight: "400",
            letterSpacing: 0,
            lineHeight: 21,
          },
          bodySmall: {
            fontSize: 12,
            fontWeight: "500",
            letterSpacing: 0.18,
            lineHeight: 16.2,
          },
          labelLarge: {
            fontSize: 13,
            fontWeight: "600",
            letterSpacing: 0,
            lineHeight: 16.25,
          },
          labelMedium: {
            fontSize: 12,
            fontWeight: "500",
            letterSpacing: 0.18,
            lineHeight: 16.2,
          },
        },
        shape: {
          extraSmall: 12,
          small: 12,
          medium: 14,
          large: 16,
          extraLarge: 20,
          full: 999,
        },
        spacing: {
          extraSmall: 4,
          small: 9.333,
          medium: 14,
          large: 18.667,
          extraLarge: 24,
          doubleExtraLarge: 38,
        },
        motion: {
          quickMs: 100,
          standardMs: 160,
          emphasizedMs: 240,
        },
        shell: {
          contentMaxWidth: 1152,
          sidebarWidth: 256,
          headerHeight: 56,
          mobileNavigationHeight: 72,
          canvasTreatment: "playful",
        },
        components: {
          button: "tonal",
          link: "underlined",
          tabs: "pill",
          navigation: "tonal",
          input: "outlined",
          select: "outlined",
          card: "outlined",
          container: "flat",
          table: "ruled",
          list: "divided",
          badge: "solid",
          chip: "solid",
          dialog: "elevated",
          popover: "elevated",
          toast: "outlined",
          switch: "solid",
          checkbox: "solid",
          radio: "solid",
          toolbar: "flat",
          pagination: "quiet",
          emptyState: "illustrated",
          loadingState: "skeleton",
          editorChrome: "neutral",
          decoration: "playful",
        },
        assetSlots: {},
        decoration: {
          celebration: ["#009824ff", "#006de2ff", "#d48a00ff", "#de4e4bff", "#a355b4ff"],
        },
        iconography: {
          packId: "phosphor",
          roles: {
            add: "plus-square",
            back: "caret-circle-left",
            next: "caret-circle-right",
            disclosure: "caret-right",
            close: "x-square",
            menu: "list",
            more: "dots-three-circle",
            search: "magnifying-glass",
            settings: "gear",
            edit: "note-pencil",
            delete: "trash-simple",
            check: "seal-check",
            retry: "arrows-clockwise",
            calendar: "calendar-blank",
            queue: "queue",
            drafts: "notebook",
            workspace: "squares-four",
            link: "arrow-square-out",
            account: "user-focus",
            notification: "bell-ringing",
            undo: "arrow-counter-clockwise",
            redo: "arrow-clockwise",
          },
        },
      },
    },
  },
  "cloud-garden": {
    id: "cloud-garden",
    displayName: "Cloud Garden",
    revision: "builtin-v1",
    supportedSchemes: ["light"],
    manifests: {
      light: {
        id: "cloud-garden-light-builtin-v1",
        familyId: "cloud-garden",
        displayName: "Cloud Garden",
        scheme: "light",
        colors: {
          background: "#f1fef5ff",
          surface: "#ffffffff",
          surfaceContainer: "#ddf6e4ff",
          surfaceContainerHigh: "#ffffffff",
          onSurface: "#091a11ff",
          onSurfaceVariant: "#4a6556ff",
          outline: "#c9decfff",
          outlineVariant: "#c9decfff",
          primary: "#072618ff",
          onPrimary: "#f1fcf4ff",
          primaryContainer: "#c0eacdff",
          onPrimaryContainer: "#002c0fff",
          secondaryContainer: "#c0eacdff",
          onSecondaryContainer: "#002c0fff",
          error: "#d02b31ff",
          onError: "#fcfcfcff",
          errorContainer: "#d02b311f",
          onErrorContainer: "#a20003ff",
          success: "#baeccaff",
          onSuccess: "#004818ff",
          warning: "#ffe8b6ff",
          onWarning: "#6f4200ff",
          link: "#007338ff",
          focus: "#091a11ff",
          scrim: "#091a1185",
          shadow: "#091a11ff",
          status: {
            draft: "#4a6556ff",
            ready: "#005274ff",
            scheduled: "#6f4200ff",
            publishing: "#072618ff",
            published: "#004818ff",
            failed: "#d02b31ff",
          },
        },
        actions: {
          focal: {
            border: "#072618ff",
            borderWidth: 1,
            container: "#072618ff",
            content: "#f1fcf4ff",
            pressedContainer: "#020c06ff",
            pressedContent: "#f1fcf4ff",
            depthColor: "#091a11ff",
            depth: 5,
            disabledOpacity: 0.42,
            underline: false,
          },
          primary: {
            border: "#003e20ff",
            borderWidth: 1,
            container: "#003e20ff",
            content: "#f1fcf4ff",
            pressedContainer: "#001708ff",
            pressedContent: "#f1fcf4ff",
            depthColor: "#00000000",
            depth: 0,
            disabledOpacity: 0.42,
            underline: false,
          },
          ordinary: {
            border: "#c9decfff",
            borderWidth: 1,
            container: "#d7f4e0ff",
            content: "#072618ff",
            pressedContainer: "#adc8b6ff",
            pressedContent: "#072618ff",
            depthColor: "#00000000",
            depth: 0,
            disabledOpacity: 0.42,
            underline: false,
          },
          quiet: {
            border: "#00000000",
            borderWidth: 0,
            container: "#00000000",
            content: "#091a11ff",
            pressedContainer: "#bbd3c3ff",
            pressedContent: "#091a11ff",
            depthColor: "#00000000",
            depth: 0,
            disabledOpacity: 0.42,
            underline: false,
          },
          destructive: {
            border: "#00000000",
            borderWidth: 0,
            container: "#d02b311f",
            content: "#a20003ff",
            pressedContainer: "#d02b3147",
            pressedContent: "#a20003ff",
            depthColor: "#00000000",
            depth: 0,
            disabledOpacity: 0.42,
            underline: false,
          },
          link: {
            border: "#00000000",
            borderWidth: 0,
            container: "#00000000",
            content: "#007338ff",
            pressedContainer: "#00000000",
            pressedContent: "#006232ff",
            depthColor: "#00000000",
            depth: 0,
            disabledOpacity: 0.42,
            underline: true,
          },
        },
        editor: {
          canvas: "#0d0b09ff",
          canvasGrid: "#2d2824ff",
          canvasSelection: "#d86d38ff",
          canvasSelectionText: "#ecebe8ff",
          transparencyLight: "#070504ff",
          transparencyDark: "#0d0b09ff",
          timeline: "#191513ff",
          timelineTrack: "#14110eff",
          timelinePlayhead: "#d86d38ff",
          waveform: "#96aec3ff",
          handle: "#f8f8f8ff",
          safeArea: "#a8bacab8",
          mediaScrim: "#091a1185",
        },
        typography: {
          displayLarge: {
            fontSize: 32,
            fontWeight: "600",
            letterSpacing: -1.12,
            lineHeight: 33.6,
          },
          headlineLarge: {
            fontSize: 24,
            fontWeight: "600",
            letterSpacing: -0.6,
            lineHeight: 27.6,
          },
          titleLarge: {
            fontSize: 24,
            fontWeight: "600",
            letterSpacing: -0.6,
            lineHeight: 27.6,
          },
          titleMedium: {
            fontSize: 13,
            fontWeight: "600",
            letterSpacing: 0,
            lineHeight: 16.25,
          },
          bodyLarge: {
            fontSize: 14,
            fontWeight: "400",
            letterSpacing: 0,
            lineHeight: 21,
          },
          bodyMedium: {
            fontSize: 14,
            fontWeight: "400",
            letterSpacing: 0,
            lineHeight: 21,
          },
          bodySmall: {
            fontSize: 12,
            fontWeight: "500",
            letterSpacing: 0.18,
            lineHeight: 16.2,
          },
          labelLarge: {
            fontSize: 13,
            fontWeight: "600",
            letterSpacing: 0,
            lineHeight: 16.25,
          },
          labelMedium: {
            fontSize: 12,
            fontWeight: "500",
            letterSpacing: 0.18,
            lineHeight: 16.2,
          },
        },
        shape: {
          extraSmall: 8,
          small: 8,
          medium: 12,
          large: 14,
          extraLarge: 14,
          full: 999,
        },
        spacing: {
          extraSmall: 4,
          small: 8,
          medium: 12,
          large: 16,
          extraLarge: 24,
          doubleExtraLarge: 36,
        },
        motion: {
          quickMs: 100,
          standardMs: 160,
          emphasizedMs: 240,
        },
        shell: {
          contentMaxWidth: 1152,
          sidebarWidth: 256,
          headerHeight: 56,
          mobileNavigationHeight: 72,
          canvasTreatment: "garden",
        },
        components: {
          button: "solid",
          link: "underlined",
          tabs: "underline",
          navigation: "tonal",
          input: "outlined",
          select: "outlined",
          card: "lifted",
          container: "tinted",
          table: "ruled",
          list: "divided",
          badge: "tonal",
          chip: "tonal",
          dialog: "elevated",
          popover: "elevated",
          toast: "outlined",
          switch: "solid",
          checkbox: "solid",
          radio: "solid",
          toolbar: "flat",
          pagination: "quiet",
          emptyState: "illustrated",
          loadingState: "skeleton",
          editorChrome: "neutral",
          decoration: "botanical",
        },
        assetSlots: {},
        decoration: {
          celebration: ["#007338ff", "#00857fff", "#0085acff", "#a4932eff", "#835198ff"],
        },
        iconography: {
          packId: "heroicons-solid",
          roles: {
            add: "plus-circle",
            back: "arrow-long-left",
            next: "arrow-long-right",
            disclosure: "chevron-double-right",
            close: "x-circle",
            menu: "bars-3-bottom-left",
            more: "ellipsis-horizontal-circle",
            search: "magnifying-glass-circle",
            settings: "cog-6-tooth",
            edit: "pencil-square",
            delete: "trash",
            check: "check-circle",
            retry: "arrow-path-rounded-square",
            calendar: "calendar-date-range",
            queue: "queue-list",
            drafts: "document-text",
            workspace: "squares-2x2",
            link: "arrow-top-right-on-square",
            account: "user-circle",
            notification: "bell-alert",
            undo: "arrow-uturn-left",
            redo: "arrow-uturn-right",
          },
        },
      },
    },
  },
  "study-hall": {
    id: "study-hall",
    displayName: "Study Hall",
    revision: "builtin-v1",
    supportedSchemes: ["light"],
    manifests: {
      light: {
        id: "study-hall-light-builtin-v1",
        familyId: "study-hall",
        displayName: "Study Hall",
        scheme: "light",
        colors: {
          background: "#f3f7ffff",
          surface: "#fcfdffff",
          surfaceContainer: "#e4ebfdff",
          surfaceContainerHigh: "#fcfdffff",
          onSurface: "#171a26ff",
          onSurfaceVariant: "#5a5f75ff",
          outline: "#ced4e5ff",
          outlineVariant: "#ced4e5ff",
          primary: "#5d4fb9ff",
          onPrimary: "#fcfcfcff",
          primaryContainer: "#ddddffff",
          onPrimaryContainer: "#261f52ff",
          secondaryContainer: "#ddddffff",
          onSecondaryContainer: "#261f52ff",
          error: "#d42f34ff",
          onError: "#fcfcfcff",
          errorContainer: "#d42f341f",
          onErrorContainer: "#a20003ff",
          success: "#c5edd2ff",
          onSuccess: "#005024ff",
          warning: "#ffe8b6ff",
          onWarning: "#6f4200ff",
          link: "#5d4fb9ff",
          focus: "#171a26ff",
          scrim: "#171a2685",
          shadow: "#171a26ff",
          status: {
            draft: "#5a5f75ff",
            ready: "#004587ff",
            scheduled: "#6f4200ff",
            publishing: "#5d4fb9ff",
            published: "#005024ff",
            failed: "#d42f34ff",
          },
        },
        actions: {
          focal: {
            border: "#5d4fb9ff",
            borderWidth: 1,
            container: "#5d4fb9ff",
            content: "#fcfcfcff",
            pressedContainer: "#4d469dff",
            pressedContent: "#fcfcfcff",
            depthColor: "#171a26ff",
            depth: 5,
            disabledOpacity: 0.42,
            underline: false,
          },
          primary: {
            border: "#1c2035ff",
            borderWidth: 1,
            container: "#1c2035ff",
            content: "#fcfcfcff",
            pressedContainer: "#050611ff",
            pressedContent: "#fcfcfcff",
            depthColor: "#00000000",
            depth: 0,
            disabledOpacity: 0.42,
            underline: false,
          },
          ordinary: {
            border: "#ced4e5ff",
            borderWidth: 1,
            container: "#e2ebffff",
            content: "#1c2035ff",
            pressedContainer: "#b9c0d7ff",
            pressedContent: "#1c2035ff",
            depthColor: "#00000000",
            depth: 0,
            disabledOpacity: 0.42,
            underline: false,
          },
          quiet: {
            border: "#00000000",
            borderWidth: 0,
            container: "#00000000",
            content: "#171a26ff",
            pressedContainer: "#c4cadbff",
            pressedContent: "#171a26ff",
            depthColor: "#00000000",
            depth: 0,
            disabledOpacity: 0.42,
            underline: false,
          },
          destructive: {
            border: "#00000000",
            borderWidth: 0,
            container: "#d42f341f",
            content: "#a20003ff",
            pressedContainer: "#d42f3447",
            pressedContent: "#a20003ff",
            depthColor: "#00000000",
            depth: 0,
            disabledOpacity: 0.42,
            underline: false,
          },
          link: {
            border: "#00000000",
            borderWidth: 0,
            container: "#00000000",
            content: "#5d4fb9ff",
            pressedContainer: "#00000000",
            pressedContent: "#4d469dff",
            depthColor: "#00000000",
            depth: 0,
            disabledOpacity: 0.42,
            underline: true,
          },
        },
        editor: {
          canvas: "#0d0b09ff",
          canvasGrid: "#2d2824ff",
          canvasSelection: "#d86d38ff",
          canvasSelectionText: "#ecebe8ff",
          transparencyLight: "#070504ff",
          transparencyDark: "#0d0b09ff",
          timeline: "#191513ff",
          timelineTrack: "#14110eff",
          timelinePlayhead: "#d86d38ff",
          waveform: "#96aec3ff",
          handle: "#f8f8f8ff",
          safeArea: "#a8bacab8",
          mediaScrim: "#171a2685",
        },
        typography: {
          displayLarge: {
            fontSize: 32,
            fontWeight: "600",
            letterSpacing: -1.12,
            lineHeight: 33.6,
          },
          headlineLarge: {
            fontSize: 24,
            fontWeight: "600",
            letterSpacing: -0.6,
            lineHeight: 27.6,
          },
          titleLarge: {
            fontSize: 24,
            fontWeight: "600",
            letterSpacing: -0.6,
            lineHeight: 27.6,
          },
          titleMedium: {
            fontSize: 13,
            fontWeight: "600",
            letterSpacing: 0,
            lineHeight: 16.25,
          },
          bodyLarge: {
            fontSize: 14,
            fontWeight: "400",
            letterSpacing: 0,
            lineHeight: 21,
          },
          bodyMedium: {
            fontSize: 14,
            fontWeight: "400",
            letterSpacing: 0,
            lineHeight: 21,
          },
          bodySmall: {
            fontSize: 12,
            fontWeight: "500",
            letterSpacing: 0.18,
            lineHeight: 16.2,
          },
          labelLarge: {
            fontSize: 13,
            fontWeight: "600",
            letterSpacing: 0,
            lineHeight: 16.25,
          },
          labelMedium: {
            fontSize: 12,
            fontWeight: "500",
            letterSpacing: 0.18,
            lineHeight: 16.2,
          },
        },
        shape: {
          extraSmall: 6,
          small: 6,
          medium: 8,
          large: 10,
          extraLarge: 14,
          full: 999,
        },
        spacing: {
          extraSmall: 4,
          small: 8,
          medium: 10,
          large: 16,
          extraLarge: 24,
          doubleExtraLarge: 34,
        },
        motion: {
          quickMs: 100,
          standardMs: 160,
          emphasizedMs: 240,
        },
        shell: {
          contentMaxWidth: 1152,
          sidebarWidth: 256,
          headerHeight: 56,
          mobileNavigationHeight: 72,
          canvasTreatment: "study",
        },
        components: {
          button: "outlined",
          link: "underlined",
          tabs: "segmented",
          navigation: "outlined",
          input: "outlined",
          select: "outlined",
          card: "flat",
          container: "flat",
          table: "striped",
          list: "divided",
          badge: "tonal",
          chip: "tonal",
          dialog: "elevated",
          popover: "elevated",
          toast: "outlined",
          switch: "solid",
          checkbox: "solid",
          radio: "solid",
          toolbar: "flat",
          pagination: "outlined",
          emptyState: "plain",
          loadingState: "skeleton",
          editorChrome: "neutral",
          decoration: "study",
        },
        assetSlots: {},
        decoration: {
          celebration: ["#5d4fb9ff", "#007faaff", "#2c965dff", "#c59128ff", "#ae599eff"],
        },
        iconography: {
          packId: "lucide",
          roles: {
            add: "plus",
            back: "arrow-left",
            next: "arrow-right",
            disclosure: "chevron-right",
            close: "x",
            menu: "menu",
            more: "ellipsis",
            search: "search",
            settings: "settings",
            edit: "pencil",
            delete: "trash-2",
            check: "check",
            retry: "rotate-cw",
            calendar: "calendar-days",
            queue: "list-clock",
            drafts: "file-pen-line",
            workspace: "panels-top-left",
            link: "external-link",
            account: "circle-user-round",
            notification: "bell",
            undo: "undo-2",
            redo: "redo-2",
          },
        },
      },
    },
  },
  corkboard: {
    id: "corkboard",
    displayName: "Corkboard",
    revision: "builtin-v1",
    supportedSchemes: ["light"],
    manifests: {
      light: {
        id: "corkboard-light-builtin-v1",
        familyId: "corkboard",
        displayName: "Corkboard",
        scheme: "light",
        colors: {
          background: "#f7ddb9ff",
          surface: "#fff6e4ff",
          surfaceContainer: "#f0cda6ff",
          surfaceContainerHigh: "#fffbefff",
          onSurface: "#24230eff",
          onSurfaceVariant: "#615c3eff",
          outline: "#ccaa84ff",
          outlineVariant: "#ccaa84ff",
          primary: "#dea143ff",
          onPrimary: "#141203ff",
          primaryContainer: "#aedffdff",
          onPrimaryContainer: "#00253fff",
          secondaryContainer: "#aedffdff",
          onSecondaryContainer: "#00253fff",
          error: "#b9322bff",
          onError: "#fff8eaff",
          errorContainer: "#c1332c1f",
          onErrorContainer: "#8a0000ff",
          success: "#b6d6a5ff",
          onSuccess: "#1e4200ff",
          warning: "#fbcb88ff",
          onWarning: "#673300ff",
          link: "#00649aff",
          focus: "#24230eff",
          scrim: "#24230e85",
          shadow: "#24230eff",
          status: {
            draft: "#615c3eff",
            ready: "#004270ff",
            scheduled: "#673300ff",
            publishing: "#7d5f27ff",
            published: "#1e4200ff",
            failed: "#b9322bff",
          },
        },
        actions: {
          focal: {
            border: "#dea143ff",
            borderWidth: 1,
            container: "#dea143ff",
            content: "#141203ff",
            pressedContainer: "#b68a36ff",
            pressedContent: "#141203ff",
            depthColor: "#24230eff",
            depth: 5,
            disabledOpacity: 0.42,
            underline: false,
          },
          primary: {
            border: "#322f0eff",
            borderWidth: 1,
            container: "#322f0eff",
            content: "#fff8eaff",
            pressedContainer: "#141203ff",
            pressedContent: "#fff8eaff",
            depthColor: "#00000000",
            depth: 0,
            disabledOpacity: 0.42,
            underline: false,
          },
          ordinary: {
            border: "#ccaa84ff",
            borderWidth: 1,
            container: "#f5e6caff",
            content: "#2c2a11ff",
            pressedContainer: "#cbbfa4ff",
            pressedContent: "#2c2a11ff",
            depthColor: "#00000000",
            depth: 0,
            disabledOpacity: 0.42,
            underline: false,
          },
          quiet: {
            border: "#00000000",
            borderWidth: 0,
            container: "#00000000",
            content: "#24230eff",
            pressedContainer: "#d0b38dff",
            pressedContent: "#24230eff",
            depthColor: "#00000000",
            depth: 0,
            disabledOpacity: 0.42,
            underline: false,
          },
          destructive: {
            border: "#00000000",
            borderWidth: 0,
            container: "#c1332c1f",
            content: "#8a0000ff",
            pressedContainer: "#c1332c47",
            pressedContent: "#8a0000ff",
            depthColor: "#00000000",
            depth: 0,
            disabledOpacity: 0.42,
            underline: false,
          },
          link: {
            border: "#00000000",
            borderWidth: 0,
            container: "#00000000",
            content: "#00649aff",
            pressedContainer: "#00000000",
            pressedContent: "#005f76ff",
            depthColor: "#00000000",
            depth: 0,
            disabledOpacity: 0.42,
            underline: true,
          },
        },
        editor: {
          canvas: "#0d0b09ff",
          canvasGrid: "#2d2824ff",
          canvasSelection: "#d86d38ff",
          canvasSelectionText: "#ecebe8ff",
          transparencyLight: "#070504ff",
          transparencyDark: "#0d0b09ff",
          timeline: "#191513ff",
          timelineTrack: "#14110eff",
          timelinePlayhead: "#d86d38ff",
          waveform: "#96aec3ff",
          handle: "#f8f8f8ff",
          safeArea: "#a8bacab8",
          mediaScrim: "#24230e85",
        },
        typography: {
          displayLarge: {
            fontSize: 32,
            fontWeight: "600",
            letterSpacing: -1.12,
            lineHeight: 33.6,
          },
          headlineLarge: {
            fontSize: 24,
            fontWeight: "600",
            letterSpacing: -0.6,
            lineHeight: 27.6,
          },
          titleLarge: {
            fontSize: 24,
            fontWeight: "600",
            letterSpacing: -0.6,
            lineHeight: 27.6,
          },
          titleMedium: {
            fontSize: 13,
            fontWeight: "600",
            letterSpacing: 0,
            lineHeight: 16.25,
          },
          bodyLarge: {
            fontSize: 14,
            fontWeight: "400",
            letterSpacing: 0,
            lineHeight: 21,
          },
          bodyMedium: {
            fontSize: 14,
            fontWeight: "400",
            letterSpacing: 0,
            lineHeight: 21,
          },
          bodySmall: {
            fontSize: 12,
            fontWeight: "500",
            letterSpacing: 0.18,
            lineHeight: 16.2,
          },
          labelLarge: {
            fontSize: 13,
            fontWeight: "600",
            letterSpacing: 0,
            lineHeight: 16.25,
          },
          labelMedium: {
            fontSize: 12,
            fontWeight: "500",
            letterSpacing: 0.18,
            lineHeight: 16.2,
          },
        },
        shape: {
          extraSmall: 4,
          small: 4,
          medium: 6,
          large: 8,
          extraLarge: 8,
          full: 999,
        },
        spacing: {
          extraSmall: 4,
          small: 8,
          medium: 10,
          large: 16,
          extraLarge: 24,
          doubleExtraLarge: 34,
        },
        motion: {
          quickMs: 100,
          standardMs: 160,
          emphasizedMs: 240,
        },
        shell: {
          contentMaxWidth: 1152,
          sidebarWidth: 256,
          headerHeight: 56,
          mobileNavigationHeight: 72,
          canvasTreatment: "tactile",
        },
        components: {
          button: "precise",
          link: "underlined",
          tabs: "underline",
          navigation: "quiet",
          input: "underlined",
          select: "underlined",
          card: "paper",
          container: "tinted",
          table: "ruled",
          list: "divided",
          badge: "tonal",
          chip: "tonal",
          dialog: "elevated",
          popover: "elevated",
          toast: "outlined",
          switch: "solid",
          checkbox: "solid",
          radio: "solid",
          toolbar: "outlined",
          pagination: "quiet",
          emptyState: "plain",
          loadingState: "skeleton",
          editorChrome: "neutral",
          decoration: "tactile",
        },
        assetSlots: {},
        decoration: {
          celebration: ["#b76c00ff", "#00649aff", "#46712bff", "#b45248ff", "#6f4c87ff"],
        },
        iconography: {
          packId: "tabler",
          roles: {
            add: "square-rounded-plus",
            back: "arrow-back-up",
            next: "arrow-forward-up",
            disclosure: "chevron-right",
            close: "square-rounded-x",
            menu: "menu-2",
            more: "dots-circle-horizontal",
            search: "zoom",
            settings: "adjustments-horizontal",
            edit: "edit-circle",
            delete: "trash-x",
            check: "checkbox",
            retry: "refresh-alert",
            calendar: "calendar-event",
            queue: "checklist",
            drafts: "note",
            workspace: "layout-dashboard",
            link: "external-link",
            account: "user-square-rounded",
            notification: "bell-ringing-2",
            undo: "corner-up-left",
            redo: "corner-up-right",
          },
        },
      },
    },
  },
  midnight: {
    id: "midnight",
    displayName: "Midnight",
    revision: "builtin-v1",
    supportedSchemes: ["dark"],
    manifests: {
      dark: {
        id: "midnight-dark-builtin-v1",
        familyId: "midnight",
        displayName: "Midnight",
        scheme: "dark",
        colors: {
          background: "#030406ff",
          surface: "#080a0fff",
          surfaceContainer: "#05060aff",
          surfaceContainerHigh: "#0c0f16ff",
          onSurface: "#e1e2daff",
          onSurfaceVariant: "#868c99ff",
          outline: "#1d222aff",
          outlineVariant: "#1d222aff",
          primary: "#a7d91dff",
          onPrimary: "#040700ff",
          primaryContainer: "#243500ff",
          onPrimaryContainer: "#d0e9a7ff",
          secondaryContainer: "#243500ff",
          onSecondaryContainer: "#d0e9a7ff",
          error: "#fc5855ff",
          onError: "#040609ff",
          errorContainer: "#fc58551f",
          onErrorContainer: "#ffaea5ff",
          success: "#082c0cff",
          onSuccess: "#81d584ff",
          warning: "#3c2300ff",
          onWarning: "#f7c15fff",
          link: "#00cfe8ff",
          focus: "#e1e2daff",
          scrim: "#e1e2da85",
          shadow: "#e1e2daff",
          status: {
            draft: "#868c99ff",
            ready: "#36caf1ff",
            scheduled: "#f7c15fff",
            publishing: "#a7d91dff",
            published: "#81d584ff",
            failed: "#fc5855ff",
          },
        },
        actions: {
          focal: {
            border: "#a7d91dff",
            borderWidth: 1,
            container: "#a7d91dff",
            content: "#040700ff",
            pressedContainer: "#b7da52ff",
            pressedContent: "#040700ff",
            depthColor: "#e1e2daff",
            depth: 5,
            disabledOpacity: 0.42,
            underline: false,
          },
          primary: {
            border: "#d8d8cdff",
            borderWidth: 1,
            container: "#d8d8cdff",
            content: "#040609ff",
            pressedContainer: "#f9f9f3ff",
            pressedContent: "#040609ff",
            depthColor: "#00000000",
            depth: 0,
            disabledOpacity: 0.42,
            underline: false,
          },
          ordinary: {
            border: "#1d222aff",
            borderWidth: 1,
            container: "#12161eff",
            content: "#d8d8d1ff",
            pressedContainer: "#020305ff",
            pressedContent: "#d8d8d1ff",
            depthColor: "#00000000",
            depth: 0,
            disabledOpacity: 0.42,
            underline: false,
          },
          quiet: {
            border: "#00000000",
            borderWidth: 0,
            container: "#00000000",
            content: "#e1e2daff",
            pressedContainer: "#1a1f22ff",
            pressedContent: "#e1e2daff",
            depthColor: "#00000000",
            depth: 0,
            disabledOpacity: 0.42,
            underline: false,
          },
          destructive: {
            border: "#00000000",
            borderWidth: 0,
            container: "#fc58551f",
            content: "#ffaea5ff",
            pressedContainer: "#fc585547",
            pressedContent: "#ffaea5ff",
            depthColor: "#00000000",
            depth: 0,
            disabledOpacity: 0.42,
            underline: false,
          },
          link: {
            border: "#00000000",
            borderWidth: 0,
            container: "#00000000",
            content: "#00cfe8ff",
            pressedContainer: "#00000000",
            pressedContent: "#4ed6d2ff",
            depthColor: "#00000000",
            depth: 0,
            disabledOpacity: 0.42,
            underline: true,
          },
        },
        editor: {
          canvas: "#070504ff",
          canvasGrid: "#26201dff",
          canvasSelection: "#f47f46ff",
          canvasSelectionText: "#ecebe8ff",
          transparencyLight: "#040302ff",
          transparencyDark: "#070504ff",
          timeline: "#14110eff",
          timelineTrack: "#100c0aff",
          timelinePlayhead: "#f47f46ff",
          waveform: "#9db4c9ff",
          handle: "#f8f8f8ff",
          safeArea: "#aec0d0b8",
          mediaScrim: "#e1e2da85",
        },
        typography: {
          displayLarge: {
            fontSize: 32,
            fontWeight: "500",
            letterSpacing: -1.12,
            lineHeight: 33.6,
          },
          headlineLarge: {
            fontSize: 24,
            fontWeight: "500",
            letterSpacing: -0.48,
            lineHeight: 27.6,
          },
          titleLarge: {
            fontSize: 24,
            fontWeight: "500",
            letterSpacing: -0.48,
            lineHeight: 27.6,
          },
          titleMedium: {
            fontSize: 13,
            fontWeight: "600",
            letterSpacing: 0,
            lineHeight: 16.25,
          },
          bodyLarge: {
            fontSize: 14,
            fontWeight: "400",
            letterSpacing: 0,
            lineHeight: 21,
          },
          bodyMedium: {
            fontSize: 14,
            fontWeight: "400",
            letterSpacing: 0,
            lineHeight: 21,
          },
          bodySmall: {
            fontSize: 12,
            fontWeight: "500",
            letterSpacing: 0.18,
            lineHeight: 16.2,
          },
          labelLarge: {
            fontSize: 13,
            fontWeight: "600",
            letterSpacing: 0,
            lineHeight: 16.25,
          },
          labelMedium: {
            fontSize: 12,
            fontWeight: "500",
            letterSpacing: 0.18,
            lineHeight: 16.2,
          },
        },
        shape: {
          extraSmall: 4,
          small: 4,
          medium: 6,
          large: 8,
          extraLarge: 14,
          full: 999,
        },
        spacing: {
          extraSmall: 4,
          small: 8,
          medium: 10,
          large: 16,
          extraLarge: 24,
          doubleExtraLarge: 34,
        },
        motion: {
          quickMs: 80,
          standardMs: 130,
          emphasizedMs: 200,
        },
        shell: {
          contentMaxWidth: 1152,
          sidebarWidth: 256,
          headerHeight: 56,
          mobileNavigationHeight: 72,
          canvasTreatment: "precision",
        },
        components: {
          button: "precise",
          link: "underlined",
          tabs: "underline",
          navigation: "quiet",
          input: "outlined",
          select: "outlined",
          card: "outlined",
          container: "flat",
          table: "ruled",
          list: "divided",
          badge: "tonal",
          chip: "tonal",
          dialog: "elevated",
          popover: "elevated",
          toast: "outlined",
          switch: "solid",
          checkbox: "solid",
          radio: "solid",
          toolbar: "outlined",
          pagination: "outlined",
          emptyState: "plain",
          loadingState: "skeleton",
          editorChrome: "precision",
          decoration: "precision",
        },
        assetSlots: {},
        decoration: {
          celebration: ["#a7d91dff", "#00c2dbff", "#b692f2ff", "#ed9e2fff", "#f2716aff"],
        },
        iconography: {
          packId: "phosphor",
          roles: {
            add: "plus-square",
            back: "caret-circle-left",
            next: "caret-circle-right",
            disclosure: "caret-right",
            close: "x-square",
            menu: "list",
            more: "dots-three-circle",
            search: "magnifying-glass",
            settings: "gear",
            edit: "note-pencil",
            delete: "trash-simple",
            check: "seal-check",
            retry: "arrows-clockwise",
            calendar: "calendar-blank",
            queue: "queue",
            drafts: "notebook",
            workspace: "squares-four",
            link: "arrow-square-out",
            account: "user-focus",
            notification: "bell-ringing",
            undo: "arrow-counter-clockwise",
            redo: "arrow-clockwise",
          },
        },
      },
    },
  },
} as const satisfies Readonly<Record<string, NativeThemeFamily>>;
