import type { NativeIconPackId, NativeIconRole } from "./contract";
import { deepFreeze } from "./freeze";

const LUCIDE_ICON_ROLES: Readonly<Record<NativeIconRole, string>> = {
  add: "plus",
  back: "arrow-left",
  next: "arrow-right",
  disclosure: "chevron-right",
  close: "x",
  menu: "menu",
  more: "ellipsis",
  search: "search",
  settings: "settings",
  edit: "pencil",
  delete: "trash-2",
  check: "check",
  retry: "rotate-cw",
  calendar: "calendar-days",
  queue: "clock-3",
  drafts: "file-pen-line",
  workspace: "panels-top-left",
  link: "external-link",
  upload: "upload",
  download: "download",
  image: "image",
  video: "video",
  account: "circle-user-round",
  notification: "bell",
  undo: "undo-2",
  redo: "redo-2",
};

const HEROICON_ROLES: Readonly<Record<NativeIconRole, string>> = {
  ...LUCIDE_ICON_ROLES,
  disclosure: "chevron-right",
  close: "x-mark",
  menu: "bars-3",
  more: "ellipsis-horizontal",
  search: "magnifying-glass",
  settings: "cog-6-tooth",
  edit: "pencil-square",
  delete: "trash",
  retry: "arrow-path",
  queue: "clock",
  drafts: "document-text",
  workspace: "squares-2x2",
  link: "arrow-top-right-on-square",
  upload: "arrow-up-tray",
  download: "arrow-down-tray",
  image: "photo",
  video: "video-camera",
  account: "user-circle",
  undo: "arrow-uturn-left",
  redo: "arrow-uturn-right",
};

export const BUILTIN_ICON_ROLE_MAPS: Readonly<
  Record<NativeIconPackId, Readonly<Record<NativeIconRole, string>>>
> = deepFreeze({
  lucide: LUCIDE_ICON_ROLES,
  "heroicons-outline": HEROICON_ROLES,
  "heroicons-solid": HEROICON_ROLES,
  phosphor: {
    ...LUCIDE_ICON_ROLES,
    disclosure: "caret-right",
    close: "x",
    menu: "list",
    more: "dots-three",
    search: "magnifying-glass",
    settings: "gear",
    edit: "pencil-simple",
    delete: "trash",
    retry: "arrow-clockwise",
    calendar: "calendar-blank",
    queue: "clock",
    drafts: "note-pencil",
    workspace: "squares-four",
    link: "arrow-square-out",
    upload: "upload-simple",
    download: "download-simple",
    video: "video-camera",
    account: "user-circle",
    undo: "arrow-u-up-left",
    redo: "arrow-u-up-right",
  },
  tabler: {
    ...LUCIDE_ICON_ROLES,
    disclosure: "chevron-right",
    close: "x",
    menu: "menu-2",
    more: "dots",
    settings: "settings",
    edit: "edit",
    delete: "trash",
    retry: "refresh",
    calendar: "calendar",
    queue: "clock",
    drafts: "file-pencil",
    workspace: "layout-dashboard",
    upload: "upload",
    download: "download",
    image: "photo",
    account: "user-circle",
    undo: "arrow-back-up",
    redo: "arrow-forward-up",
  },
});
