// Generated by scripts/generate-theme-icon-packs.mjs. Do not edit by hand.
import type { ImageSourcePropType } from "react-native";
import type { NativeIconPackId } from "./contract.js";
import type { NativeTabIconRole } from "./native-tab-icon-selection.js";

export const NATIVE_TAB_ICON_SOURCES = {
  lucide: {
    drafts: require("../../assets/theme-icons/lucide/drafts.png"),
    calendar: require("../../assets/theme-icons/lucide/calendar.png"),
    queue: require("../../assets/theme-icons/lucide/queue.png"),
  },
  "heroicons-outline": {
    drafts: require("../../assets/theme-icons/heroicons-outline/drafts.png"),
    calendar: require("../../assets/theme-icons/heroicons-outline/calendar.png"),
    queue: require("../../assets/theme-icons/heroicons-outline/queue.png"),
  },
  "heroicons-solid": {
    drafts: require("../../assets/theme-icons/heroicons-solid/drafts.png"),
    calendar: require("../../assets/theme-icons/heroicons-solid/calendar.png"),
    queue: require("../../assets/theme-icons/heroicons-solid/queue.png"),
  },
  phosphor: {
    drafts: require("../../assets/theme-icons/phosphor/drafts.png"),
    calendar: require("../../assets/theme-icons/phosphor/calendar.png"),
    queue: require("../../assets/theme-icons/phosphor/queue.png"),
  },
  tabler: {
    drafts: require("../../assets/theme-icons/tabler/drafts.png"),
    calendar: require("../../assets/theme-icons/tabler/calendar.png"),
    queue: require("../../assets/theme-icons/tabler/queue.png"),
  },
} satisfies Readonly<
  Record<NativeIconPackId, Readonly<Record<NativeTabIconRole, ImageSourcePropType>>>
>;
