import collection from '@iconify-json/lucide/icons.json';
import type { ThemeIconRole } from '../../contracts.js';
import { createThemeIconPack } from './create-pack.js';

const names = {
	add: 'plus',
	analytics: 'chart-no-axes-combined',
	appearance: 'palette',
	archive: 'archive',
	'arrow-down': 'arrow-down',
	'arrow-left': 'arrow-left',
	'arrow-right': 'arrow-right',
	'arrow-up': 'arrow-up',
	at: 'at-sign',
	audio: 'volume-2',
	calendar: 'calendar-days',
	camera: 'camera',
	check: 'check',
	'chevron-down': 'chevron-down',
	'chevron-left': 'chevron-left',
	'chevron-right': 'chevron-right',
	'chevron-up': 'chevron-up',
	close: 'x',
	compose: 'square-pen',
	communications: 'messages-square',
	controls: 'sliders-horizontal',
	copy: 'copy',
	delete: 'trash-2',
	download: 'download',
	drag: 'grip-vertical',
	edit: 'pencil',
	editors: 'clapperboard',
	'external-link': 'external-link',
	eye: 'eye',
	'eye-off': 'eye-off',
	filter: 'funnel',
	feedback: 'message-square-text',
	growth: 'user-round-plus',
	help: 'circle-help',
	home: 'house',
	image: 'image',
	media: 'images',
	link: 'link',
	lock: 'lock',
	logout: 'log-out',
	mail: 'mail',
	menu: 'menu',
	'more-horizontal': 'ellipsis',
	'more-vertical': 'ellipsis-vertical',
	notification: 'bell',
	organization: 'building-2',
	publications: 'files',
	redo: 'redo-2',
	refresh: 'refresh-cw',
	remove: 'minus',
	search: 'search',
	send: 'send',
	settings: 'settings',
	share: 'share-2',
	sparkles: 'sparkles',
	upload: 'upload',
	user: 'user-round',
	users: 'users-round',
	video: 'video',
	workspace: 'panels-top-left',
	undo: 'undo-2'
} satisfies Record<ThemeIconRole, string>;

export default createThemeIconPack('lucide', collection, names);
