import collection from '@iconify-json/ph/icons.json';
import type { ThemeIconRole } from '../../contracts.js';
import { createThemeIconPack } from './create-pack.js';

const names = {
	add: 'plus',
	analytics: 'chart-line-up',
	appearance: 'palette',
	archive: 'archive',
	'arrow-down': 'arrow-down',
	'arrow-left': 'arrow-left',
	'arrow-right': 'arrow-right',
	'arrow-up': 'arrow-up',
	at: 'at',
	audio: 'speaker-high',
	calendar: 'calendar',
	camera: 'camera',
	check: 'check',
	'chevron-down': 'caret-down',
	'chevron-left': 'caret-left',
	'chevron-right': 'caret-right',
	'chevron-up': 'caret-up',
	close: 'x',
	compose: 'note-pencil',
	communications: 'chats',
	controls: 'sliders-horizontal',
	copy: 'copy',
	delete: 'trash',
	download: 'download-simple',
	drag: 'dots-six-vertical',
	edit: 'pencil',
	editors: 'film-strip',
	'external-link': 'arrow-square-out',
	eye: 'eye',
	'eye-off': 'eye-slash',
	filter: 'funnel',
	feedback: 'chat-text',
	growth: 'user-plus',
	help: 'question',
	home: 'house',
	image: 'image',
	media: 'images',
	link: 'link',
	lock: 'lock',
	logout: 'sign-out',
	mail: 'envelope',
	menu: 'list',
	'more-horizontal': 'dots-three',
	'more-vertical': 'dots-three-vertical',
	notification: 'bell',
	organization: 'buildings',
	publications: 'files',
	redo: 'arrow-clockwise',
	refresh: 'arrows-clockwise',
	remove: 'minus',
	search: 'magnifying-glass',
	send: 'paper-plane-tilt',
	settings: 'gear',
	share: 'share-network',
	sparkles: 'sparkle',
	upload: 'upload-simple',
	user: 'user',
	users: 'users',
	video: 'video-camera',
	workspace: 'squares-four',
	undo: 'arrow-counter-clockwise'
} satisfies Record<ThemeIconRole, string>;

export default createThemeIconPack('phosphor', collection, names);
