import collection from '@iconify-json/tabler/icons.json';
import type { ThemeIconRole } from '../../contracts.js';
import { createThemeIconPack } from './create-pack.js';

const names = {
	add: 'plus',
	analytics: 'chart-line',
	appearance: 'palette',
	archive: 'archive',
	'arrow-down': 'arrow-down',
	'arrow-left': 'arrow-left',
	'arrow-right': 'arrow-right',
	'arrow-up': 'arrow-up',
	at: 'at',
	audio: 'volume',
	calendar: 'calendar',
	camera: 'camera',
	check: 'check',
	'chevron-down': 'chevron-down',
	'chevron-left': 'chevron-left',
	'chevron-right': 'chevron-right',
	'chevron-up': 'chevron-up',
	close: 'x',
	compose: 'pencil-plus',
	communications: 'messages',
	controls: 'adjustments-horizontal',
	copy: 'copy',
	delete: 'trash',
	download: 'download',
	drag: 'grip-vertical',
	edit: 'pencil',
	editors: 'movie',
	'external-link': 'external-link',
	eye: 'eye',
	'eye-off': 'eye-off',
	filter: 'filter',
	feedback: 'message',
	growth: 'user-plus',
	help: 'help-circle',
	home: 'home',
	image: 'photo',
	media: 'photo',
	link: 'link',
	lock: 'lock',
	logout: 'logout',
	mail: 'mail',
	menu: 'menu-2',
	'more-horizontal': 'dots',
	'more-vertical': 'dots-vertical',
	notification: 'bell',
	organization: 'building',
	publications: 'files',
	redo: 'arrow-forward-up',
	refresh: 'refresh',
	remove: 'minus',
	search: 'search',
	send: 'send',
	settings: 'settings',
	share: 'share-2',
	sparkles: 'sparkles',
	upload: 'upload',
	user: 'user',
	users: 'users',
	video: 'video',
	workspace: 'layout-grid',
	undo: 'arrow-back-up'
} satisfies Record<ThemeIconRole, string>;

export default createThemeIconPack('tabler', collection, names);
