import { readdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(scriptDir, "../..");
const docsRoot = path.join(root, "docs-site");
const output = path.join(root, "packages/social-images/src/docs-catalog.js");

async function markdownFiles(directory) {
  const files = [];
  for (const entry of await readdir(directory, { withFileTypes: true })) {
    if (entry.name.startsWith(".") || entry.name === "node_modules") continue;
    const target = path.join(directory, entry.name);
    if (entry.isDirectory()) files.push(...(await markdownFiles(target)));
    else if (entry.isFile() && entry.name.endsWith(".md")) files.push(target);
  }
  return files;
}

function pageTitle(page, source) {
  const heading = source.match(/^#\s+(.+)$/m)?.[1]?.trim();
  if (heading) return heading.replaceAll("`", "");
  if (page === "index.md") return "OpenPost";
  return path
    .basename(page, ".md")
    .split("-")
    .map((word) =>
      word === "api" ? "API" : `${word[0].toUpperCase()}${word.slice(1)}`,
    )
    .join(" ");
}

export async function generateSocialCatalog({ check = false } = {}) {
  const pages = [];
  for (const file of (await markdownFiles(docsRoot)).sort()) {
    const page = path.relative(docsRoot, file).split(path.sep).join("/");
    const source = await readFile(file, "utf8");
    pages.push({ page, title: pageTitle(page, source) });
  }

  const contents = `// Generated by scripts/social-images/catalog.mjs. Do not edit by hand.\n// prettier-ignore\nexport const docsPageCatalog = Object.freeze(${JSON.stringify(pages, null, 2)});\n`;
  if (check) {
    const current = await readFile(output, "utf8").catch(() => "");
    if (current !== contents) {
      throw new Error(
        "The social image docs catalog is stale. Run bun run generate:social-catalog.",
      );
    }
    return;
  }
  await writeFile(output, contents);
}

if (
  process.argv[1] &&
  path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)
) {
  await generateSocialCatalog({ check: process.argv.includes("--check") });
}
