// Generated by scripts/social-images/catalog.mjs. Do not edit by hand.
// prettier-ignore
export const docsPageCatalog = Object.freeze([
  {
    "page": "api-reference/index.mdx",
    "title": "API reference",
    "description": "Authenticate and call the OpenPost HTTP API.",
    "route": "/api-reference",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "primary",
      "section": "api"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "api"
    }
  },
  {
    "page": "guides/accounts.mdx",
    "title": "Connect accounts",
    "description": "Add and manage social accounts in a workspace.",
    "route": "/guides/accounts",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "primary",
      "section": "user-guide"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "user-guide"
    }
  },
  {
    "page": "guides/analytics.mdx",
    "title": "Analytics",
    "description": "Understand account growth and content performance using the data your providers return.",
    "route": "/guides/analytics",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "user-guide"
    }
  },
  {
    "page": "guides/automation.mdx",
    "title": "Automation",
    "description": "Use the CLI, MCP, or the OpenPost n8n node.",
    "route": "/guides/automation",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "user-guide"
    }
  },
  {
    "page": "guides/image-editor.mdx",
    "title": "Image Editor",
    "description": "Create reusable designs, carousel pages, and images for your posts.",
    "route": "/guides/image-editor",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "user-guide"
    }
  },
  {
    "page": "guides/inbox.mdx",
    "title": "Inbox and notifications",
    "description": "Read comments, reply to conversations, and choose the alerts you receive.",
    "route": "/guides/inbox",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "user-guide"
    }
  },
  {
    "page": "guides/media-library.mdx",
    "title": "Media library",
    "description": "Upload, organize, reuse, and clean up your workspace media.",
    "route": "/guides/media-library",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "user-guide"
    }
  },
  {
    "page": "guides/media-limits.mdx",
    "title": "Media limits",
    "description": "Default attachment limits used by OpenPost before publishing.",
    "route": "/guides/media-limits",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "user-guide"
    }
  },
  {
    "page": "guides/media.mdx",
    "title": "Media and editors",
    "description": "Store reusable media and prepare images or video for publications.",
    "route": "/guides/media",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "user-guide"
    }
  },
  {
    "page": "guides/publishing.mdx",
    "title": "Create and publish",
    "description": "Write, review, and publish destination-specific versions of a publication.",
    "route": "/guides/publishing",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "user-guide"
    }
  },
  {
    "page": "guides/quick-cut.mdx",
    "title": "Trim with Quick Cut",
    "description": "Keep the parts you need and export a cut without unnecessary re-encoding.",
    "route": "/guides/quick-cut",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "user-guide"
    }
  },
  {
    "page": "guides/quickstart.mdx",
    "title": "Quickstart",
    "description": "Connect an account and publish your first OpenPost publication.",
    "route": "/guides/quickstart",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "primary",
      "section": "user-guide"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "user-guide"
    }
  },
  {
    "page": "guides/recording.mdx",
    "title": "Record screen and camera",
    "description": "Capture your screen, camera, and microphone, then bring the recording into your edit.",
    "route": "/guides/recording",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "user-guide"
    }
  },
  {
    "page": "guides/results.mdx",
    "title": "Review results",
    "description": "Find delivery status, inbox activity, and analytics.",
    "route": "/guides/results",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "user-guide"
    }
  },
  {
    "page": "guides/scheduling.mdx",
    "title": "Schedule and calendar",
    "description": "Plan publication times and recover scheduled delivery.",
    "route": "/guides/scheduling",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "user-guide"
    }
  },
  {
    "page": "guides/troubleshooting.mdx",
    "title": "Troubleshooting",
    "description": "Fix common connection, media, scheduling, and delivery problems.",
    "route": "/guides/troubleshooting",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "user-guide"
    }
  },
  {
    "page": "guides/video-editor.mdx",
    "title": "Video Editor",
    "description": "Build, save, and export a social video from a multitrack timeline.",
    "route": "/guides/video-editor",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "user-guide"
    }
  },
  {
    "page": "guides/workspaces.mdx",
    "title": "Workspaces and settings",
    "description": "Keep accounts, content, media, and access separated by workspace.",
    "route": "/guides/workspaces",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "user-guide"
    }
  },
  {
    "page": "index.mdx",
    "title": "OpenPost documentation",
    "description": "Connect your accounts, prepare a post, and publish it from one workspace.",
    "route": "/",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "primary",
      "section": "user-guide"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "user-guide"
    }
  },
  {
    "page": "mcp/antigravity.mdx",
    "title": "Connect Antigravity",
    "description": "Use the OpenPost local bridge from Antigravity.",
    "route": "/mcp/antigravity",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "mcp"
    }
  },
  {
    "page": "mcp/chatgpt.mdx",
    "title": "Connect ChatGPT",
    "description": "Add OpenPost as a custom MCP app in ChatGPT.",
    "route": "/mcp/chatgpt",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "mcp"
    }
  },
  {
    "page": "mcp/claude-code.mdx",
    "title": "Connect Claude Code",
    "description": "Use OpenPost from Claude Code in your terminal.",
    "route": "/mcp/claude-code",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "mcp"
    }
  },
  {
    "page": "mcp/claude-desktop.mdx",
    "title": "Connect Claude Desktop",
    "description": "Connect through Claude account settings or a local OpenPost bridge.",
    "route": "/mcp/claude-desktop",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "mcp"
    }
  },
  {
    "page": "mcp/claude.mdx",
    "title": "Connect Claude web",
    "description": "Connect OpenPost to Claude through a custom connector.",
    "route": "/mcp/claude",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "mcp"
    }
  },
  {
    "page": "mcp/codex.mdx",
    "title": "Connect Codex",
    "description": "Add OpenPost to Codex with remote MCP and browser sign-in.",
    "route": "/mcp/codex",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "mcp"
    }
  },
  {
    "page": "mcp/cursor.mdx",
    "title": "Connect Cursor",
    "description": "Add OpenPost to Cursor using remote MCP and OAuth.",
    "route": "/mcp/cursor",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "mcp"
    }
  },
  {
    "page": "mcp/devin.mdx",
    "title": "Connect Devin",
    "description": "Give Devin access to your OpenPost workspace through MCP.",
    "route": "/mcp/devin",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "mcp"
    }
  },
  {
    "page": "mcp/gemini-cli.mdx",
    "title": "Connect Gemini CLI",
    "description": "Review and prepare OpenPost publications from Gemini CLI.",
    "route": "/mcp/gemini-cli",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "mcp"
    }
  },
  {
    "page": "mcp/github-copilot.mdx",
    "title": "Connect GitHub Copilot",
    "description": "Use OpenPost from Copilot agent chat in VS Code.",
    "route": "/mcp/github-copilot",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "mcp"
    }
  },
  {
    "page": "mcp/grok.mdx",
    "title": "Connect Grok",
    "description": "Add OpenPost as a custom Grok connector.",
    "route": "/mcp/grok",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "mcp"
    }
  },
  {
    "page": "mcp/hermes.mdx",
    "title": "Connect Hermes Agent",
    "description": "Add OpenPost to Hermes Agent as an OAuth MCP server.",
    "route": "/mcp/hermes",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "mcp"
    }
  },
  {
    "page": "mcp/index.mdx",
    "title": "AI assistants",
    "description": "Connect ChatGPT, Claude, Cursor, or another MCP client to OpenPost.",
    "route": "/mcp",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "primary",
      "section": "mcp"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "mcp"
    }
  },
  {
    "page": "mcp/openclaw.mdx",
    "title": "Connect OpenClaw",
    "description": "Connect an OpenClaw agent to your OpenPost workspace.",
    "route": "/mcp/openclaw",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "mcp"
    }
  },
  {
    "page": "mcp/opencode.mdx",
    "title": "Connect OpenCode",
    "description": "Add OpenPost to OpenCode using remote MCP and OAuth.",
    "route": "/mcp/opencode",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "mcp"
    }
  },
  {
    "page": "mcp/perplexity.mdx",
    "title": "Connect Perplexity",
    "description": "Use OpenPost through a custom remote Perplexity connector.",
    "route": "/mcp/perplexity",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "mcp"
    }
  },
  {
    "page": "mcp/tools.mdx",
    "title": "Tools and permissions",
    "description": "Understand OpenPost MCP tools, scopes, and safe request patterns.",
    "route": "/mcp/tools",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "mcp"
    }
  },
  {
    "page": "mcp/vs-code.mdx",
    "title": "Connect VS Code",
    "description": "Use OpenPost tools in VS Code agent chat.",
    "route": "/mcp/vs-code",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "mcp"
    }
  },
  {
    "page": "self-hosting/ai.mdx",
    "title": "AI providers",
    "description": "Configure OpenRouter for post generation and media captions.",
    "route": "/self-hosting/ai",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "self-hosting"
    }
  },
  {
    "page": "self-hosting/configuration.mdx",
    "title": "Configuration",
    "description": "Configure URLs, storage, provider apps, and optional self-hosted services.",
    "route": "/self-hosting/configuration",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "self-hosting"
    }
  },
  {
    "page": "self-hosting/email.mdx",
    "title": "Email delivery",
    "description": "Configure authentication and notification email for self-hosted instances.",
    "route": "/self-hosting/email",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "self-hosting"
    }
  },
  {
    "page": "self-hosting/index.mdx",
    "title": "Self-host OpenPost",
    "description": "Run OpenPost on your own server with Docker Compose.",
    "route": "/self-hosting",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "primary",
      "section": "self-hosting"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "self-hosting"
    }
  },
  {
    "page": "self-hosting/integrations/bluesky-mastodon.mdx",
    "title": "Bluesky and Mastodon",
    "description": "Configure the two providers that need no static OAuth app in the common case.",
    "route": "/self-hosting/integrations/bluesky-mastodon",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "self-hosting"
    }
  },
  {
    "page": "self-hosting/integrations/discord-telegram.mdx",
    "title": "Discord and Telegram",
    "description": "Configure supported Discord webhooks and gated Telegram bot mode.",
    "route": "/self-hosting/integrations/discord-telegram",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "self-hosting"
    }
  },
  {
    "page": "self-hosting/integrations/index.mdx",
    "title": "Provider integrations",
    "description": "Configure provider apps for a self-hosted OpenPost instance.",
    "route": "/self-hosting/integrations",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "self-hosting"
    }
  },
  {
    "page": "self-hosting/integrations/linkedin.mdx",
    "title": "LinkedIn",
    "description": "Configure LinkedIn OAuth for member profiles and Organization Pages.",
    "route": "/self-hosting/integrations/linkedin",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "self-hosting"
    }
  },
  {
    "page": "self-hosting/integrations/meta-platforms.mdx",
    "title": "Facebook, Instagram, and Threads",
    "description": "Configure the Meta apps used by OpenPost's three Meta integrations.",
    "route": "/self-hosting/integrations/meta-platforms",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "self-hosting"
    }
  },
  {
    "page": "self-hosting/integrations/pinterest.mdx",
    "title": "Pinterest",
    "description": "Configure Pinterest for controlled development and certification.",
    "route": "/self-hosting/integrations/pinterest",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "self-hosting"
    }
  },
  {
    "page": "self-hosting/integrations/tiktok.mdx",
    "title": "TikTok",
    "description": "Configure TikTok Login Kit and Content Posting API access.",
    "route": "/self-hosting/integrations/tiktok",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "self-hosting"
    }
  },
  {
    "page": "self-hosting/integrations/x.mdx",
    "title": "X",
    "description": "Configure an X OAuth 1.0a application.",
    "route": "/self-hosting/integrations/x",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "self-hosting"
    }
  },
  {
    "page": "self-hosting/integrations/youtube.mdx",
    "title": "YouTube",
    "description": "Configure Google OAuth and YouTube video uploads.",
    "route": "/self-hosting/integrations/youtube",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "self-hosting"
    }
  },
  {
    "page": "self-hosting/maintenance.mdx",
    "title": "Maintenance",
    "description": "Back up, upgrade, monitor, and recover a self-hosted instance.",
    "route": "/self-hosting/maintenance",
    "agentRepresentation": {
      "membership": "ordinary"
    },
    "agentDiscovery": {
      "membership": "unlisted"
    },
    "agentCorpus": {
      "membership": "included",
      "section": "self-hosting"
    }
  }
]);
