// Generated by scripts/social-images/catalog.mjs. Do not edit by hand.
// prettier-ignore
export const docsPageCatalog = Object.freeze([
  {
    "page": "cli/authentication.md",
    "title": "Sign In From the CLI"
  },
  {
    "page": "cli/automation.md",
    "title": "Automate the CLI"
  },
  {
    "page": "cli/index.md",
    "title": "OpenPost CLI"
  },
  {
    "page": "cli/installation.md",
    "title": "CLI Installation"
  },
  {
    "page": "cli/posting.md",
    "title": "Posting with the CLI"
  },
  {
    "page": "configuration/cors-and-urls.md",
    "title": "CORS And URLs"
  },
  {
    "page": "configuration/database.md",
    "title": "Database"
  },
  {
    "page": "configuration/environment-variables.md",
    "title": "Environment Variables"
  },
  {
    "page": "configuration/feedback.md",
    "title": "User Feedback"
  },
  {
    "page": "configuration/media-storage.md",
    "title": "Media Storage"
  },
  {
    "page": "configuration/overview.md",
    "title": "Configuration Overview"
  },
  {
    "page": "configuration/production-checklist.md",
    "title": "Production Checklist"
  },
  {
    "page": "configuration/provider-applications.md",
    "title": "Provider Applications"
  },
  {
    "page": "configuration/telemetry.md",
    "title": "Product telemetry and error tracking"
  },
  {
    "page": "configuration/update-status.md",
    "title": "Update Status"
  },
  {
    "page": "development/analytics.md",
    "title": "Analytics Architecture"
  },
  {
    "page": "development/api-reference.md",
    "title": "API Reference"
  },
  {
    "page": "development/api-tokens.md",
    "title": "API Tokens"
  },
  {
    "page": "development/architecture.md",
    "title": "Architecture"
  },
  {
    "page": "development/backend.md",
    "title": "Backend"
  },
  {
    "page": "development/background-jobs.md",
    "title": "Background Jobs"
  },
  {
    "page": "development/billing-and-usage.md",
    "title": "Billing And Usage Foundation"
  },
  {
    "page": "development/compatibility-policy.md",
    "title": "API and schema compatibility"
  },
  {
    "page": "development/contributing.md",
    "title": "Contributing"
  },
  {
    "page": "development/frontend.md",
    "title": "Frontend"
  },
  {
    "page": "development/image-editor-completeness.md",
    "title": "Image Editor Completeness Checklist"
  },
  {
    "page": "development/index.md",
    "title": "Developer Docs"
  },
  {
    "page": "development/mcp.md",
    "title": "MCP And ChatGPT App"
  },
  {
    "page": "development/platform-adapters.md",
    "title": "Platform Adapters"
  },
  {
    "page": "development/production-readiness.md",
    "title": "Production Architecture and Checks"
  },
  {
    "page": "development/releases.md",
    "title": "Releases and Versioning"
  },
  {
    "page": "development/setup.md",
    "title": "Development Setup"
  },
  {
    "page": "development/testing.md",
    "title": "Testing"
  },
  {
    "page": "development/third-party-notices.md",
    "title": "Third-Party Notices"
  },
  {
    "page": "guide/concepts.md",
    "title": "Concepts"
  },
  {
    "page": "guide/quickstart.md",
    "title": "Quickstart"
  },
  {
    "page": "guide/what-is-openpost.md",
    "title": "What Is OpenPost?"
  },
  {
    "page": "guide/why-selfhost.md",
    "title": "When Self-Hosting Fits"
  },
  {
    "page": "index.md",
    "title": "OpenPost"
  },
  {
    "page": "installation/android.md",
    "title": "Android App"
  },
  {
    "page": "installation/binary.md",
    "title": "Single Binary"
  },
  {
    "page": "installation/build-from-source.md",
    "title": "Build From Source"
  },
  {
    "page": "installation/docker-compose.md",
    "title": "Docker Compose"
  },
  {
    "page": "installation/docker-run.md",
    "title": "Docker Run"
  },
  {
    "page": "installation/nix-module.md",
    "title": "Nix Module"
  },
  {
    "page": "installation/reverse-proxy.md",
    "title": "Reverse Proxy"
  },
  {
    "page": "mcp/index.md",
    "title": "Use OpenPost With an AI Assistant"
  },
  {
    "page": "operations/backups.md",
    "title": "Backups"
  },
  {
    "page": "operations/container-image.md",
    "title": "Container Image Support and Assurance"
  },
  {
    "page": "operations/health-checks.md",
    "title": "Health Checks"
  },
  {
    "page": "operations/logs.md",
    "title": "Logs"
  },
  {
    "page": "operations/troubleshooting.md",
    "title": "Troubleshooting"
  },
  {
    "page": "operations/upgrades.md",
    "title": "Upgrades"
  },
  {
    "page": "providers/bluesky.md",
    "title": "Bluesky"
  },
  {
    "page": "providers/discord.md",
    "title": "Discord Webhooks"
  },
  {
    "page": "providers/facebook.md",
    "title": "Facebook"
  },
  {
    "page": "providers/instagram.md",
    "title": "Instagram"
  },
  {
    "page": "providers/launch-matrix.md",
    "title": "Provider Readiness and Launch Gate"
  },
  {
    "page": "providers/linkedin.md",
    "title": "LinkedIn"
  },
  {
    "page": "providers/mastodon.md",
    "title": "Mastodon"
  },
  {
    "page": "providers/overview.md",
    "title": "Platform Overview"
  },
  {
    "page": "providers/platform-limits.md",
    "title": "Platform Implementations & Limitations"
  },
  {
    "page": "providers/roadmap.md",
    "title": "Platform Roadmap"
  },
  {
    "page": "providers/threads.md",
    "title": "Threads"
  },
  {
    "page": "providers/tiktok.md",
    "title": "TikTok"
  },
  {
    "page": "providers/troubleshooting.md",
    "title": "Provider Troubleshooting"
  },
  {
    "page": "providers/x.md",
    "title": "X"
  },
  {
    "page": "providers/youtube.md",
    "title": "YouTube"
  },
  {
    "page": "reference/api.md",
    "title": "API Reference"
  },
  {
    "page": "reference/callback-urls.md",
    "title": "Callback URLs"
  },
  {
    "page": "reference/cli.md",
    "title": "CLI Reference"
  },
  {
    "page": "reference/docker-compose.md",
    "title": "Docker Compose Reference"
  },
  {
    "page": "reference/env-vars.md",
    "title": "Environment Variables"
  },
  {
    "page": "reference/surface-parity.md",
    "title": "Product Surface Parity"
  },
  {
    "page": "self-hosting/index.md",
    "title": "Self-Hosting Docs"
  },
  {
    "page": "usage/account-security.md",
    "title": "Account Security"
  },
  {
    "page": "usage/accounts.md",
    "title": "Accounts"
  },
  {
    "page": "usage/agent-assisted-publishing.md",
    "title": "Agent-Assisted, Human-Reviewed Publishing"
  },
  {
    "page": "usage/analytics.md",
    "title": "Analytics"
  },
  {
    "page": "usage/auto-reposts.md",
    "title": "Auto Reposts"
  },
  {
    "page": "usage/communications.md",
    "title": "Engagement, Inbox, and Notifications"
  },
  {
    "page": "usage/composing-posts.md",
    "title": "Composing Posts"
  },
  {
    "page": "usage/destination-options.md",
    "title": "Account Options"
  },
  {
    "page": "usage/image-editor.md",
    "title": "OpenPost Image Editor"
  },
  {
    "page": "usage/index.md",
    "title": "User Docs"
  },
  {
    "page": "usage/media-library.md",
    "title": "Media"
  },
  {
    "page": "usage/scheduling.md",
    "title": "Scheduling"
  },
  {
    "page": "usage/settings.md",
    "title": "Settings"
  },
  {
    "page": "usage/studio.md",
    "title": "OpenPost Studio"
  },
  {
    "page": "usage/threads.md",
    "title": "Threads"
  },
  {
    "page": "usage/video-editor.md",
    "title": "OpenPost Video Editor"
  },
  {
    "page": "usage/workspaces.md",
    "title": "Workspaces"
  }
]);
