package handlers

import "github.com/openpost/backend/internal/jobregistry"

const (
	tagAuth              = "Auth"
	tagAccounts          = "Accounts"
	tagAnalytics         = "Analytics"
	tagCapabilities      = "Capabilities"
	tagCommunications    = "Communications"
	tagMedia             = "Media"
	tagNotifications     = "Notifications"
	tagMCP               = "MCP"
	tagPostingSchedules  = "Posting Schedules"
	tagPosts             = "Posts"
	tagProviderReadiness = "Provider Readiness"
	tagPublications      = "Publications"
	tagPrompts           = "Prompts"
	tagProfiles          = "Profiles"
	tagReposts           = "Repost Automation"
	tagSocialSets        = "Social Sets"
	tagImageEditor       = "OpenPost Image Editor"
	tagVideoEditor       = "OpenPost Video Editor"
	tagWorkspaces        = "Workspaces"

	fieldError = "error"

	errWorkspaceIDRequired      = "workspace_id is required"
	errValidateWorkspaceAccess  = "failed to validate workspace access"
	errWorkspaceAccessDenied    = "you do not have access to this workspace"
	errMediaNotFound            = "media not found"
	mediaSortSize               = "size"
	postStatusPending           = "pending"
	jobStatusPending            = jobregistry.StatusPending
	jobStatusProcessing         = jobregistry.StatusProcessing
	postIDKey                   = "post_id"
	jobTypePublishPost          = jobregistry.TypePublishPost
	jobTypePublishPublication   = jobregistry.TypePublishPublication
	postPathByID                = "/posts/{id}"
	postPathVariants            = "/posts/{id}/variants"
	postingLabelEarlyMorning    = "Early Morning"
	postingLabelMorning         = "Morning"
	postingLabelLateMorning     = "Late Morning"
	postingLabelLunch           = "Lunch"
	postingLabelAfternoon       = "Afternoon"
	postingLabelLateAfternoon   = "Late Afternoon"
	postingLabelEvening         = "Evening"
	postingLabelNight           = "Night"
	postingLabelLateNight       = "Late Night"
	promptCategoryBoldProvoking = "Bold & Provoking"
	promptCategoryStorytelling  = "Storytelling"
	promptCategoryRepurposeFAQ  = "Repurpose & FAQ"
	promptCategoryDailyUpdates  = "Daily Updates"
	promptCategoryHowTo         = "How-To"
	promptCategoryReflection    = "Reflection"
	promptCategoryEngagement    = "Engagement"
	promptCategoryToolsWorkflow = "Tools & Workflow"
	promptCategoryBehindScenes  = "Behind the Scenes"
	promptCategoryWins          = "Wins"
	promptCategoryCuratedLists  = "Curated Lists"
	promptCategoryPredictions   = "Predictions"
	promptCategoryQuickEasy     = "Quick & Easy"
	promptCategoryDeveloper     = "Developer"
	promptCategoryBuildInPublic = "Building in Public"
	promptCategoryFounderStory  = "Founder Story"
	promptCategoryIndustry      = "Industry Commentary"
	promptCategoryTeamCulture   = "Team & Culture"
	promptCategoryLessons       = "Lessons & Frameworks"
	promptCategoryEngageStart   = "Engagement Starters"
)
