package handlers

const (
	tagAuth              = "Auth"
	tagAccounts          = "Accounts"
	tagAnalytics         = "Analytics"
	tagCapabilities      = "Capabilities"
	tagCommunications    = "Communications"
	tagMedia             = "Media"
	tagNotifications     = "Notifications"
	tagMCP               = "MCP"
	tagPostingSchedules  = "Posting Schedules"
	tagPosts             = "Posts"
	tagProviderReadiness = "Provider Readiness"
	tagPublications      = "Publications"
	tagPrompts           = "Prompts"
	tagStudio            = "Studio"
	tagWorkspaces        = "Workspaces"

	fieldError = "error"

	errWorkspaceIDRequired      = "workspace_id is required"
	errValidateWorkspaceAccess  = "failed to validate workspace access"
	errWorkspaceAccessDenied    = "you do not have access to this workspace"
	errMediaNotFound            = "media not found"
	mediaSortSize               = "size"
	postStatusPending           = "pending"
	jobStatusPending            = "pending"
	jobStatusProcessing         = "processing"
	postIDKey                   = "post_id"
	jobTypePublishPost          = "publish_post"
	jobTypePublishPublication   = "publish_publication"
	postPathByID                = "/posts/{id}"
	postPathVariants            = "/posts/{id}/variants"
	postingLabelEarlyMorning    = "Early Morning"
	postingLabelMorning         = "Morning"
	postingLabelLateMorning     = "Late Morning"
	postingLabelLunch           = "Lunch"
	postingLabelAfternoon       = "Afternoon"
	postingLabelLateAfternoon   = "Late Afternoon"
	postingLabelEvening         = "Evening"
	postingLabelNight           = "Night"
	postingLabelLateNight       = "Late Night"
	promptCategoryBoldProvoking = "Bold & Provoking"
	promptCategoryStorytelling  = "Storytelling"
	promptCategoryRepurposeFAQ  = "Repurpose & FAQ"
	promptCategoryDailyUpdates  = "Daily Updates"
	promptCategoryHowTo         = "How-To"
	promptCategoryReflection    = "Reflection"
	promptCategoryEngagement    = "Engagement"
	promptCategoryToolsWorkflow = "Tools & Workflow"
	promptCategoryBehindScenes  = "Behind the Scenes"
	promptCategoryWins          = "Wins"
	promptCategoryCuratedLists  = "Curated Lists"
	promptCategoryPredictions   = "Predictions"
	promptCategoryQuickEasy     = "Quick & Easy"
	promptCategoryDeveloper     = "Developer"
)
