import type { VoiceProfilesCopy } from './types';

export const DEFAULT_VOICE_PROFILES_COPY: VoiceProfilesCopy = {
	title: 'Voice profiles',
	description:
		'Keep each person or brand consistent while OpenPost adapts the writing to each platform.',
	newProfile: 'New voice',
	profilesHeading: 'Profiles',
	profilesLabel: 'Voice profiles',
	loading: 'Loading voice profiles',
	loadFailed: 'OpenPost could not load voice profiles.',
	retry: 'Try again',
	emptyTitle: 'No voice profiles yet',
	emptyDescription: 'Create one voice for a person or brand, then assign it to connected accounts.',
	defaultBadge: 'Workspace default',
	assignedCount: (count) => `${count} ${count === 1 ? 'account' : 'accounts'}`,
	unsavedSwitch: 'Save or cancel your changes before opening another voice profile.',
	name: 'Profile name',
	namePlaceholder: 'Rodrigo or OpenPost',
	identityHeading: 'Identity',
	identityDescription:
		'Start with a short summary and a few stable traits. This is enough for most voices.',
	identitySummary: 'Who is speaking?',
	identitySummaryPlaceholder:
		'A technical founder who writes directly, shares evidence, and uses dry humor when it helps.',
	traits: 'Voice traits',
	traitsDescription: 'Add short traits that should stay true on every platform.',
	traitsPlaceholder: 'Direct, technical, casual',
	expertise: 'First-hand expertise',
	expertiseDescription: 'Subjects this voice can discuss from real experience.',
	expertisePlaceholder: 'Social publishing, product engineering',
	advancedHeading: 'Advanced voice details',
	advancedDescription:
		'Add language preferences, limits, examples, and accepted edits when you have them.',
	languageHeading: 'Language and opinions',
	vocabulary: 'Natural vocabulary',
	vocabularyDescription: 'Words this voice uses without forcing them into every post.',
	vocabularyPlaceholder: 'Ship, draft, provider',
	recurringExpressions: 'Recurring expressions',
	recurringExpressionsDescription: 'Phrases that already sound natural for this person or brand.',
	recurringExpressionsPlaceholder: 'The practical part is...',
	opinions: 'Established opinions',
	opinionsDescription: 'Views OpenPost may draw on when the source supports them.',
	opinionsPlaceholder: 'Every destination should get its own native rendition.',
	toneHeading: 'Tone and boundaries',
	humor: 'Humor',
	humorPlaceholder: 'Dry and brief. Never joke about customers or support problems.',
	formality: 'Formality',
	formalityPlaceholder: 'Casual but precise. Use plain technical terms when they are accurate.',
	boundaries: 'Boundaries',
	boundariesDescription: 'Things this voice should not claim, reveal, or turn into a joke.',
	boundariesPlaceholder: 'Do not speak for customers',
	avoidHeading: 'What to avoid',
	forbiddenPhrases: 'Forbidden phrases',
	forbiddenPhrasesDescription: 'Exact wording OpenPost must not use.',
	forbiddenPhrasesPlaceholder: 'Game changer, unlock your potential',
	dislikedPatterns: 'Disliked writing patterns',
	dislikedPatternsDescription: 'Broader habits that make a draft sound wrong.',
	dislikedPatternsPlaceholder: 'One sentence per line, fake suspense hooks',
	learningHeading: 'Writing evidence',
	learningDescription: 'Examples and edits teach the voice better than more adjectives.',
	examples: 'Representative examples',
	addExample: 'Add example',
	exampleText: 'Example text',
	exampleTextPlaceholder: 'Paste a post or passage that sounds right.',
	examplePlatform: 'Source platform',
	examplePlatformPlaceholder: 'LinkedIn',
	exampleReason: 'Why it fits',
	exampleReasonPlaceholder: 'Direct opening, concrete detail, no sales language.',
	corrections: 'Accepted corrections',
	addCorrection: 'Add correction',
	correctionOriginal: 'Original wording',
	correctionOriginalPlaceholder: 'The draft wording that felt wrong.',
	correctionPreferred: 'Preferred wording',
	correctionPreferredPlaceholder: 'The wording you accepted.',
	correctionLesson: 'What should OpenPost learn?',
	correctionLessonPlaceholder: 'Keep the technical claim, cut the hype.',
	interviewAnswers: 'Interview answers',
	addInterviewAnswer: 'Add answer',
	interviewQuestion: 'Question',
	interviewQuestionPlaceholder: 'What do you believe about social publishing?',
	interviewAnswer: 'Answer',
	interviewAnswerPlaceholder: "Answer in the profile owner's own words.",
	removeItem: 'Remove',
	addItem: 'Add',
	save: 'Save changes',
	create: 'Create voice',
	saving: 'Saving',
	cancel: 'Cancel',
	setDefault: 'Make workspace default',
	settingDefault: 'Setting default',
	defaultHelp: 'Accounts without a specific assignment use this voice.',
	delete: 'Delete voice',
	deleteTitle: 'Delete voice profile?',
	deleteDescription: (name) =>
		`Delete ${name}? Accounts assigned to it will use the workspace default. This cannot be undone.`,
	deleteConfirm: 'Delete voice',
	deleteDefaultHelp: 'Choose another workspace default before deleting this profile.',
	accountsHeading: 'Account assignments',
	accountsDescription:
		'Choose the identity behind each connected account. Platform style is applied separately.',
	accountsLoading: 'Loading connected accounts',
	accountVoiceLabel: (account) => `Voice for ${account}`,
	workspaceDefaultOption: (name) => `${name} (workspace default)`,
	noAccounts: 'Connect a social account to assign a voice.',
	assignmentFailed: 'OpenPost could not update this account assignment.',
	nameRequired: 'Enter a profile name.',
	nameTooLong: 'Keep the profile name to 80 characters or fewer.',
	exampleTextRequired: 'Remove the empty example or add its text.',
	correctionPairRequired: 'Each correction needs both the original and preferred wording.',
	interviewPairRequired: 'Each interview entry needs both a question and an answer.',
	saveFailed: 'OpenPost could not save this voice profile.',
	deleteFailed: 'OpenPost could not delete this voice profile.',
	defaultFailed: 'OpenPost could not change the workspace default.',
	dismissError: 'Dismiss error'
};

export function voiceProfilesCopy(overrides: Partial<VoiceProfilesCopy> = {}): VoiceProfilesCopy {
	return { ...DEFAULT_VOICE_PROFILES_COPY, ...overrides };
}
