import { m } from '$lib/paraglide/messages';
import type { VoiceProfilesCopy } from './types';

export function localizedVoiceProfilesCopy(): VoiceProfilesCopy {
	return {
		title: m.settings_voice_profiles(),
		description: m.settings_voice_profiles_description(),
		newProfile: m.settings_voice_new_profile(),
		profilesHeading: m.settings_voice_profiles_heading(),
		profilesLabel: m.settings_voice_profiles_label(),
		loading: m.settings_voice_loading(),
		loadFailed: m.settings_voice_load_failed(),
		retry: m.common_retry(),
		emptyTitle: m.settings_voice_empty_title(),
		emptyDescription: m.settings_voice_empty_description(),
		defaultBadge: m.settings_voice_default_badge(),
		assignedCount: (count) =>
			count === 1
				? m.settings_voice_assigned_account_one({ count })
				: m.settings_voice_assigned_account_many({ count }),
		unsavedSwitch: m.settings_voice_unsaved_switch(),
		name: m.settings_voice_name(),
		namePlaceholder: m.settings_voice_name_placeholder(),
		identityHeading: m.settings_voice_identity_heading(),
		identityDescription: m.settings_voice_identity_description(),
		identitySummary: m.settings_voice_identity_summary(),
		identitySummaryPlaceholder: m.settings_voice_identity_summary_placeholder(),
		traits: m.settings_voice_traits(),
		traitsDescription: m.settings_voice_traits_description(),
		traitsPlaceholder: m.settings_voice_traits_placeholder(),
		expertise: m.settings_voice_expertise(),
		expertiseDescription: m.settings_voice_expertise_description(),
		expertisePlaceholder: m.settings_voice_expertise_placeholder(),
		advancedHeading: m.settings_voice_advanced_heading(),
		advancedDescription: m.settings_voice_advanced_description(),
		languageHeading: m.settings_voice_language_heading(),
		vocabulary: m.settings_voice_vocabulary(),
		vocabularyDescription: m.settings_voice_vocabulary_description(),
		vocabularyPlaceholder: m.settings_voice_vocabulary_placeholder(),
		recurringExpressions: m.settings_voice_recurring_expressions(),
		recurringExpressionsDescription: m.settings_voice_recurring_expressions_description(),
		recurringExpressionsPlaceholder: m.settings_voice_recurring_expressions_placeholder(),
		opinions: m.settings_voice_opinions(),
		opinionsDescription: m.settings_voice_opinions_description(),
		opinionsPlaceholder: m.settings_voice_opinions_placeholder(),
		toneHeading: m.settings_voice_tone_heading(),
		humor: m.settings_voice_humor(),
		humorPlaceholder: m.settings_voice_humor_placeholder(),
		formality: m.settings_voice_formality(),
		formalityPlaceholder: m.settings_voice_formality_placeholder(),
		boundaries: m.settings_voice_boundaries(),
		boundariesDescription: m.settings_voice_boundaries_description(),
		boundariesPlaceholder: m.settings_voice_boundaries_placeholder(),
		avoidHeading: m.settings_voice_avoid_heading(),
		forbiddenPhrases: m.settings_voice_forbidden_phrases(),
		forbiddenPhrasesDescription: m.settings_voice_forbidden_phrases_description(),
		forbiddenPhrasesPlaceholder: m.settings_voice_forbidden_phrases_placeholder(),
		dislikedPatterns: m.settings_voice_disliked_patterns(),
		dislikedPatternsDescription: m.settings_voice_disliked_patterns_description(),
		dislikedPatternsPlaceholder: m.settings_voice_disliked_patterns_placeholder(),
		learningHeading: m.settings_voice_learning_heading(),
		learningDescription: m.settings_voice_learning_description(),
		examples: m.settings_voice_examples(),
		addExample: m.settings_voice_add_example(),
		exampleText: m.settings_voice_example_text(),
		exampleTextPlaceholder: m.settings_voice_example_text_placeholder(),
		examplePlatform: m.settings_voice_example_platform(),
		examplePlatformPlaceholder: m.settings_voice_example_platform_placeholder(),
		exampleReason: m.settings_voice_example_reason(),
		exampleReasonPlaceholder: m.settings_voice_example_reason_placeholder(),
		corrections: m.settings_voice_corrections(),
		addCorrection: m.settings_voice_add_correction(),
		correctionOriginal: m.settings_voice_correction_original(),
		correctionOriginalPlaceholder: m.settings_voice_correction_original_placeholder(),
		correctionPreferred: m.settings_voice_correction_preferred(),
		correctionPreferredPlaceholder: m.settings_voice_correction_preferred_placeholder(),
		correctionLesson: m.settings_voice_correction_lesson(),
		correctionLessonPlaceholder: m.settings_voice_correction_lesson_placeholder(),
		interviewAnswers: m.settings_voice_interview_answers(),
		addInterviewAnswer: m.settings_voice_add_interview_answer(),
		interviewQuestion: m.settings_voice_interview_question(),
		interviewQuestionPlaceholder: m.settings_voice_interview_question_placeholder(),
		interviewAnswer: m.settings_voice_interview_answer(),
		interviewAnswerPlaceholder: m.settings_voice_interview_answer_placeholder(),
		removeItem: m.settings_voice_remove_item(),
		addItem: m.settings_voice_add_item(),
		save: m.settings_voice_save(),
		create: m.settings_voice_create(),
		saving: m.common_saving(),
		cancel: m.common_cancel(),
		setDefault: m.settings_voice_set_default(),
		settingDefault: m.settings_voice_setting_default(),
		defaultHelp: m.settings_voice_default_help(),
		delete: m.settings_voice_delete(),
		deleteTitle: m.settings_voice_delete_title(),
		deleteDescription: (name) => m.settings_voice_delete_description({ name }),
		deleteConfirm: m.settings_voice_delete_confirm(),
		deleteDefaultHelp: m.settings_voice_delete_default_help(),
		accountsHeading: m.settings_voice_accounts_heading(),
		accountsDescription: m.settings_voice_accounts_description(),
		accountsLoading: m.settings_voice_accounts_loading(),
		accountVoiceLabel: (account) => m.settings_voice_account_label({ account }),
		workspaceDefaultOption: (name) => m.settings_voice_workspace_default_option({ name }),
		noAccounts: m.settings_voice_no_accounts(),
		assignmentFailed: m.settings_voice_assignment_failed(),
		nameRequired: m.settings_voice_name_required(),
		nameTooLong: m.settings_voice_name_too_long(),
		exampleTextRequired: m.settings_voice_example_text_required(),
		correctionPairRequired: m.settings_voice_correction_pair_required(),
		interviewPairRequired: m.settings_voice_interview_pair_required(),
		saveFailed: m.settings_voice_save_failed(),
		deleteFailed: m.settings_voice_delete_failed(),
		defaultFailed: m.settings_voice_default_failed(),
		dismissError: m.common_dismiss()
	};
}
