// Code generated by scripts/plan-catalog.mjs from packages/plan-catalog/src/catalog.json; DO NOT EDIT.

package billing

import "github.com/openpost/backend/internal/services/entitlements"

const (
	PlanCatalogVersion      = "2026-09-08"
	PlanCatalogTrialDays    = 14
	PlanCatalogCardRequired = true
	PlanCatalogDueTodayUSD  = 0
)

var canonicalPlanOrder = []string{"founder", "team", "agency"}

var canonicalPlanCatalog = map[string]PlanConfig{
	"founder": {
		Name: "Solo", MonthlyPriceUSD: 29, AnnualPriceUSD: 290,
		Limits: map[entitlements.LimitKey]int64{
			entitlements.LimitWorkspaces:                1,
			entitlements.LimitSocialAccounts:            10,
			entitlements.LimitScheduledPostsMonthly:     500,
			entitlements.LimitMediaBytesStored:          10000000000,
			entitlements.LimitMediaBytesUploadedMonthly: 10000000000,
			entitlements.LimitTeamMembers:               1,
		},
	},
	"team": {
		Name: "Team", MonthlyPriceUSD: 59, AnnualPriceUSD: 590,
		Limits: map[entitlements.LimitKey]int64{
			entitlements.LimitWorkspaces:                3,
			entitlements.LimitSocialAccounts:            10,
			entitlements.LimitScheduledPostsMonthly:     500,
			entitlements.LimitMediaBytesStored:          10000000000,
			entitlements.LimitMediaBytesUploadedMonthly: 10000000000,
			entitlements.LimitTeamMembers:               5,
		},
	},
	"agency": {
		Name: "Agency", MonthlyPriceUSD: 99, AnnualPriceUSD: 990,
		Limits: map[entitlements.LimitKey]int64{
			entitlements.LimitWorkspaces:                10,
			entitlements.LimitSocialAccounts:            10,
			entitlements.LimitScheduledPostsMonthly:     500,
			entitlements.LimitMediaBytesStored:          10000000000,
			entitlements.LimitMediaBytesUploadedMonthly: 10000000000,
			entitlements.LimitTeamMembers:               10,
		},
	},
}
