export type AssetSurface = "frontend" | "docs" | "marketing";

export const publishedProviderAssetSlugs = [
  "x",
  "mastodon",
  "bluesky",
  "linkedin",
  "threads",
  "facebook",
  "instagram",
  "tiktok",
  "youtube",
  "pinterest",
  "telegram",
  "discord",
] as const;

export const assetSurfaceManifest = {
  frontend: [
    "brand/icon.svg",
    "brand/features/image-editor.svg",
    "brand/features/video-editor.svg",
    "brand/pwa-192.png",
    "brand/pwa-512.png",
    "brand/pwa-maskable-512.png",
    "brand/apple-touch-icon.png",
  ],
  docs: ["brand/icon.svg", "brand/logo-docs.svg", "screenshots/main-dark.png"],
  marketing: [
    "brand/fonts/Geist-Regular.ttf",
    "brand/fonts/Geist-SemiBold.ttf",
    "brand/fonts/Manrope-SemiBold.ttf",
    "brand/logo.svg",
    "brand/og-image.png",
    "brand/features/image-editor.svg",
    "brand/features/video-editor.svg",
    "brand/features/compose.svg",
    "brand/features/calendar.svg",
    "brand/features/analytics.svg",
    "screenshots/main-dark.webp",
    "screenshots/calendar-detail.webp",
    "screenshots/analytics-detail.webp",
    "screenshots/image-canvas-detail.webp",
    "screenshots/image-controls-detail.webp",
    "screenshots/video-preview-detail.webp",
    "screenshots/video-timeline-detail.webp",

    "screenshots/calendar-dark.webp",
    "screenshots/analytics-dark.webp",
    ...publishedProviderAssetSlugs.map((slug) => `logos/${slug}.svg`),
    "postiz-socials/Bluesky.svg",
    "postiz-socials/Discord.svg",
    "postiz-socials/Facebook.svg",
    "postiz-socials/Instagram.svg",
    "postiz-socials/Linkedin.svg",
    "postiz-socials/Mastodon.svg",
    "postiz-socials/Threads.svg",
    "postiz-socials/TikTok.svg",
    "postiz-socials/X.svg",
    "postiz-socials/Youtube.svg",
    "screenshots/image-editor-dark.webp",
    "screenshots/main-dark.png",
    "screenshots/media-dark.png",
    "screenshots/settings-dark.png",
    "screenshots/video-editor-dark.webp",
  ],
} as const satisfies Record<AssetSurface, readonly string[]>;
