import { readFile, writeFile } from "node:fs/promises";
import process from "node:process";

const sourcePath = new URL(
  "../packages/plan-catalog/src/catalog.json",
  import.meta.url,
);
const outputPath = new URL(
  "../backend/internal/services/billing/catalog_generated.go",
  import.meta.url,
);

const limitKeys = [
  ["workspaces", "LimitWorkspaces"],
  ["social_accounts", "LimitSocialAccounts"],
  ["scheduled_posts_monthly", "LimitScheduledPostsMonthly"],
  ["media_bytes_stored", "LimitMediaBytesStored"],
  ["media_bytes_uploaded_monthly", "LimitMediaBytesUploadedMonthly"],
  ["team_members", "LimitTeamMembers"],
];
const longestGoLimitKey = Math.max(
  ...limitKeys.map(([, goKey]) => `entitlements.${goKey}`.length),
);

function goString(value) {
  return JSON.stringify(value);
}

function renderCatalog(catalog) {
  const order = catalog.plans.map((plan) => goString(plan.id)).join(", ");
  const plans = catalog.plans
    .map((plan) => {
      const limits = limitKeys
        .map(
          ([jsonKey, goKey]) =>
            `\t\t\t${`entitlements.${goKey}:`.padEnd(longestGoLimitKey + 2)}${plan.limits[jsonKey]},`,
        )
        .join("\n");

      return `\t${goString(plan.id)}: {
\t\tName: ${goString(plan.name)}, MonthlyPriceUSD: ${plan.monthly_price_usd}, AnnualPriceUSD: ${plan.annual_price_usd},
\t\tLimits: map[entitlements.LimitKey]int64{
${limits}
\t\t},
\t},`;
    })
    .join("\n");

  return `// Code generated by scripts/plan-catalog.mjs from packages/plan-catalog/src/catalog.json; DO NOT EDIT.

package billing

import "github.com/openpost/backend/internal/services/entitlements"

const (
	PlanCatalogVersion      = ${goString(catalog.version)}
	PlanCatalogTrialDays    = ${catalog.purchase_terms.trial_days}
	PlanCatalogCardRequired = ${catalog.purchase_terms.card_required}
	PlanCatalogDueTodayUSD  = ${catalog.purchase_terms.due_today_usd}
)

var canonicalPlanOrder = []string{${order}}

var canonicalPlanCatalog = map[string]PlanConfig{
${plans}
}
`;
}

const catalog = JSON.parse(await readFile(sourcePath, "utf8"));
const generated = renderCatalog(catalog);

if (process.argv.includes("--check")) {
  const current = await readFile(outputPath, "utf8");
  if (current !== generated) {
    console.error(
      "Plan catalogue output is stale. Run: bun scripts/plan-catalog.mjs",
    );
    process.exit(1);
  }
} else {
  await writeFile(outputPath, generated);
}
