#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=4
: "$RED"

banner "OpenPost n8n publishing setup"

stage "Reserve the package with a placeholder"
say "npm cannot trust a GitHub workflow until the package name exists."
say "This publishes a non-functional 0.0.0 placeholder. CI will publish the real 0.1.0 package later with provenance."
if npm view '@getopenpost/n8n-nodes-openpost@0.0.0' version >/dev/null 2>&1; then
  note "The 0.0.0 placeholder already exists, so this stage is complete."
else
  command -v npm >/dev/null 2>&1 || { warn "npm is required"; exit 1; }
  stage_tmp=$(mktemp -d)
  trap 'rm -rf "$stage_tmp"' EXIT
  npm_auth_config=""
  npm_run() {
    if [[ -n "$npm_auth_config" ]]; then
      NPM_CONFIG_USERCONFIG="$npm_auth_config" npm "$@"
    else
      npm "$@"
    fi
  }
  if ! npm_run whoami --registry https://registry.npmjs.org/ >/dev/null 2>&1; then
    npm_auth_config="$stage_tmp/npmrc"
    touch "$npm_auth_config"
    chmod 600 "$npm_auth_config"
    step "Sign in to npm. Complete the browser and two-factor prompts."
    note "The sign-in uses a private temporary config, so read-only or managed ~/.npmrc files are safe."
    npm_run login --registry https://registry.npmjs.org/
    npm_run whoami --registry https://registry.npmjs.org/ >/dev/null
  fi
  placeholder_dir="$stage_tmp/placeholder"
  mkdir "$placeholder_dir"
  printf '%s\n' \
    '{' \
    '  "name": "@getopenpost/n8n-nodes-openpost",' \
    '  "version": "0.0.0",' \
    '  "description": "Registry placeholder for the official OpenPost n8n package.",' \
    '  "license": "MIT",' \
    '  "repository": "https://github.com/getopenpost/openpost.git",' \
    '  "publishConfig": { "access": "public" }' \
    '}' > "$placeholder_dir/package.json"
  printf '%s\n' \
    '# OpenPost n8n package placeholder' \
    '' \
    'This 0.0.0 package only reserves the npm name for trusted publishing.' \
    'Install version 0.1.0 or newer after the GitHub release workflow publishes it.' \
    > "$placeholder_dir/README.md"
  step "Review the exact placeholder payload shown below. It contains no executable code."
  npm_run pack "$placeholder_dir" --dry-run
  if confirm "Publish the non-functional @getopenpost/n8n-nodes-openpost@0.0.0 placeholder now?"; then
    npm_run publish "$placeholder_dir" --access public --registry https://registry.npmjs.org/
    note "npm accepted the publish. Waiting up to one minute for public registry reads to catch up."
    published_version=""
    for attempt in {1..12}; do
      if published_version=$(npm_run view '@getopenpost/n8n-nodes-openpost@0.0.0' version --registry https://registry.npmjs.org/ 2>/dev/null); then
        break
      fi
      [[ "$attempt" -lt 12 ]] && sleep 5
    done
    if [[ "$published_version" == "0.0.0" ]]; then
      note "The public registry now returns version $published_version."
    else
      warn "npm accepted the publish, but public registry reads are still syncing. Do not publish again."
      note "Re-run this wizard later. It will detect version 0.0.0 and continue at trusted publishing."
    fi
  else
    warn "Placeholder publication skipped. Trusted publishing cannot be configured yet."
    exit 1
  fi
fi
pause "Continue to trusted publishing?"

stage "Trust the release workflow"
say "Connect npm to the one workflow that may publish the real package."
open_url "https://www.npmjs.com/package/@getopenpost/n8n-nodes-openpost/access"
step "Open Settings, then find Trusted Publisher and choose GitHub Actions."
step "Organization or user: getopenpost"
step "Repository: openpost"
step "Workflow filename: release.yml"
step "Leave Environment name empty."
step "Under Allowed actions, enable npm publish only, then save."
step "Under Publishing access, choose Require two-factor authentication and disallow tokens, then save."
pause "Press Enter after both settings are saved."

stage "Let the app release publish 0.1.0"
say "No npm token or GitHub secret is needed. The release workflow uses short-lived OIDC credentials."
step "Merge this code to main through the normal project flow."
step "When you are ready to ship the app, run the normal 'bun run release -- prod' flow from a clean main checkout."
step "The workflow deploys the exact backend revision before it publishes the n8n package."
open_url "https://github.com/getopenpost/openpost/actions/workflows/release.yml"
step "Confirm 'Publish and verify n8n package' passes. It checks provenance, integrity, the n8n scanner, and a clean install."
pause "Press Enter after the release job succeeds, or Ctrl-C to return later."

stage "Submit the verified package to n8n"
if npm view '@getopenpost/n8n-nodes-openpost@0.1.0' version >/dev/null 2>&1; then
  open_url "https://creators.n8n.io/nodes"
  step "Sign in to the n8n Creator Portal and start a node submission."
  step "Package name: @getopenpost/n8n-nodes-openpost"
  step "Source repository: https://github.com/getopenpost/openpost"
  step "Use the package README for setup and operation details, then submit it for verification."
  note "Portal review is separate from npm publication. Keep public copy accurate until n8n accepts it."
else
  SKIPPED+=("n8n Creator Portal submission after @getopenpost/n8n-nodes-openpost@0.1.0 is published")
  warn "Version 0.1.0 is not on npm yet, so Creator Portal submission is not ready."
fi

finish
