// Code generated by scripts/legal-policy-manifest.mjs; DO NOT EDIT.
package legalpolicy

const (
	SchemaVersion = 1

	TermsVersion       = "2026-08-05"
	TermsEffectiveDate = "2026-08-05"
	TermsURL           = "https://openpost.social/terms"

	PrivacyVersion       = "2026-09-01"
	PrivacyEffectiveDate = "2026-09-01"
	PrivacyURL           = "https://openpost.social/privacy"

	RefundsVersion            = "2026-08-05"
	RefundsEffectiveDate      = "2026-08-05"
	RefundsURL                = "https://openpost.social/refunds"
	RefundsRequiresAcceptance = false
)
