// Code generated by scripts/plan-catalog.mjs from packages/plan-catalog/src/catalog.json; DO NOT EDIT.

package billing

import "github.com/openpost/backend/internal/services/entitlements"

const (
	PlanCatalogVersion      = "2026-08-12"
	PlanCatalogTrialDays    = 14
	PlanCatalogCardRequired = true
	PlanCatalogDueTodayUSD  = 0
)

var canonicalPlanOrder = []string{"starter", "founder", "pro", "team", "agency"}

var canonicalPlanCatalog = map[string]PlanConfig{
	"starter": {
		Name: "Starter", MonthlyPriceUSD: 15, AnnualPriceUSD: 150,
		Limits: map[entitlements.LimitKey]int64{
			entitlements.LimitWorkspaces:                1,
			entitlements.LimitSocialAccounts:            3,
			entitlements.LimitScheduledPostsMonthly:     100,
			entitlements.LimitMediaBytesStored:          1000000000,
			entitlements.LimitMediaBytesUploadedMonthly: 1000000000,
			entitlements.LimitTeamMembers:               1,
		},
	},
	"founder": {
		Name: "Founder", MonthlyPriceUSD: 25, AnnualPriceUSD: 250,
		Limits: map[entitlements.LimitKey]int64{
			entitlements.LimitWorkspaces:                3,
			entitlements.LimitSocialAccounts:            6,
			entitlements.LimitScheduledPostsMonthly:     500,
			entitlements.LimitMediaBytesStored:          5000000000,
			entitlements.LimitMediaBytesUploadedMonthly: 5000000000,
			entitlements.LimitTeamMembers:               1,
		},
	},
	"pro": {
		Name: "Pro", MonthlyPriceUSD: 49, AnnualPriceUSD: 490,
		Limits: map[entitlements.LimitKey]int64{
			entitlements.LimitWorkspaces:                10,
			entitlements.LimitSocialAccounts:            15,
			entitlements.LimitScheduledPostsMonthly:     2500,
			entitlements.LimitMediaBytesStored:          25000000000,
			entitlements.LimitMediaBytesUploadedMonthly: 25000000000,
			entitlements.LimitTeamMembers:               1,
		},
	},
	"team": {
		Name: "Team", MonthlyPriceUSD: 99, AnnualPriceUSD: 990,
		Limits: map[entitlements.LimitKey]int64{
			entitlements.LimitWorkspaces:                10,
			entitlements.LimitSocialAccounts:            25,
			entitlements.LimitScheduledPostsMonthly:     5000,
			entitlements.LimitMediaBytesStored:          50000000000,
			entitlements.LimitMediaBytesUploadedMonthly: 50000000000,
			entitlements.LimitTeamMembers:               3,
		},
	},
	"agency": {
		Name: "Agency", MonthlyPriceUSD: 199, AnnualPriceUSD: 1990,
		Limits: map[entitlements.LimitKey]int64{
			entitlements.LimitWorkspaces:                50,
			entitlements.LimitSocialAccounts:            150,
			entitlements.LimitScheduledPostsMonthly:     25000,
			entitlements.LimitMediaBytesStored:          250000000000,
			entitlements.LimitMediaBytesUploadedMonthly: 250000000000,
			entitlements.LimitTeamMembers:               5,
		},
	},
}
